### ISSUE TITLE
Composite Agents should take in an error handler and counter on construction to better handle composite doWork/onClose/onStart exceptions in children

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#100]
This allows more flexibility in exception handling and will allow composite agents to handle errors more correctly/fairly. Consider for instance that an agent which always throws an exception will starve other agents.
Sadly this is API breaking.

**Comment by mjpt777** [comment]
Can this not be passed to the constructor of the Agent? It feels like against current usage.

**Comment by mjpt777** [comment]
On reflection collaborators are best past in by constructor injection so the object is always in a valid state. The only reason for passing in later would be to void a circular dependency. The suggested level of breaking change is too much.

**Comment by nitsanw** [comment]
Seems reasonable. I will rename to reflect on Composite agents where most of the issue is.

**Comment by mjpt777** [comment]
Your point on exceptions is well made. I think a better solution is to have a MultiAgentRunner rather than a composite agent.

**Comment by nitsanw** [comment]
Is this a way to work around breaking existing code or a genuine difference?

**Comment by mjpt777** [comment]
It is a better way to separate the concerns and centralise the error handling. The composite agent approach was wrong in this respect. I'm working on fix this all.
