### ISSUE TITLE
Different lifecycle for AgentInvoker vs AgentRunner when onStart hits exception

### ISSUE THREAD

**Issue by nitsanw** [real-logic/agrona#101]
Nit picking, but:
https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/AgentInvoker.java#L107
The invoke will be skipped if closed, but a failure onStart does not trigger a close()
Compare with AgentRunner where we clearly skip doWork calls if onStart() fails:
https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/AgentRunner.java#L154
For consistency we can add a running flag, or switch to using a state enum, such that invoke does nothing if the onStart failed. This is still quite opaque to caller which will need some external visibility to the Invoker broken state.

**Comment by mjpt777** [comment]
Calling close() should be the responsibility of the caller to pair up with start().

**Comment by nitsanw** [comment]
coupled with further commit: https://github.com/real-logic/agrona/commit/8368144e804515daa635aeedf7822ad4b046be25
This is now resolved
