### ISSUE TITLE
Support passing endian values on AtomicBuffer

### ISSUE THREAD

**Issue by mikeb01** [real-logic/agrona#104]
AtomicBuffer only provides operations in native byte order, it would be useful if the endianess of the value could be supplied on these methods as well as the standard DirectBuffer methods.

**Comment by mjpt777** [comment]
Very happy to accept a PR for this.

**Comment by mjpt777** [comment]
This can work for some methods but would be awkward and/or inefficient for getAndAdd style semantics.
