### ISSUE TITLE
Safer UnsafeBuffer.toString() and UnsafeBuffer.hashcode()

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/agrona#106]
If an UnsafeBuffer is wrapping an underlying mappedbytebuffer and it gets unmapped/closed then operations like toString() and hashcode() cause a segfault, because they rely on the values of the mappedbytebuffer. I'm wondering if there's not a safer way of doing things? Or perhaps at least documenting: don't call toString() or hashcode() after you've been unmapped.

**Comment by mjpt777** [comment]
It should be the case that you don't call anything, except possibly wrapping another buffer, after an unmap.

**Comment by RichardWarburton** [comment]
So for context in this case I was logging when a buffer was being closed in order to discover which buffer wasn't being closed. I wouldn't expect to be able to do anything else to a buffer, but the behaviour of segfaulting the JVM on I called toString() was quite surprising.

**Comment by mjpt777** [comment]
BTW there is no toString() method on UnsafeBuffer other than the one inherited from Object. There is an equals and hashCode. What was the issue with toString() you are seeing?

**Comment by RichardWarburton** [comment]
Yeah, sorry I should have explained it better. UnsafeBuffer inherits the toString() method from Object, which then invokes hashcode() on itself, thus calling UnsafeBuffer.hashcode(). the hashcode() causes the segfault.

**Comment by mjpt777** [comment]
That makes more sense. We should provide one that does a reasonable thing so debuggers don't cause a crash in that case.
