### ISSUE TITLE
Java 9 illegal reflective access warning

### ISSUE THREAD

**Issue by guidomedina** [real-logic/agrona#108]
I'm quite sure it can be ignored for a time, but reporting it anyway:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.agrona.IoUtil (file:/home/signals/green-engine-runner/scripts/aeron/repo/agrona-0.9.7.jar) to method sun.nio.ch.FileChannelImpl.map0(int,long,long)
WARNING: Please consider reporting this to the maintainers of org.agrona.IoUtil
```

**Comment by mjpt777** [comment]
Thanks. There are a number of things we could change to better integrate work with Java 9. I plan to work on this later this year when 9 starts to bed in and look for alternatives.

**Comment by BrassyPanache** [comment]
I thought just to add to this that I could use the VM flag: --illegal-access=warn
Without this flag all reflection warnings after the first are suppressed.  Here is the full output:

> WARNING: Illegal reflective access by org.agrona.IoUtil (file:/home/ckornie/.gradle/caches/modules-2/files-2.1/org.agrona/agrona/0.9.11/d539577c77df892e1efe97e7575e17f6e34c44ef/agrona-0.9.11.jar) to method sun.nio.ch.FileChannelImpl.map0(int,long,long)
> WARNING: Illegal reflective access by org.agrona.IoUtil (file:/home/ckornie/.gradle/caches/modules-2/files-2.1/org.agrona/agrona/0.9.11/d539577c77df892e1efe97e7575e17f6e34c44ef/agrona-0.9.11.jar) to method sun.nio.ch.FileChannelImpl.unmap0(long,long)
> WARNING: Illegal reflective access by org.agrona.IoUtil (file:/home/ckornie/.gradle/caches/modules-2/files-2.1/org.agrona/agrona/0.9.11/d539577c77df892e1efe97e7575e17f6e34c44ef/agrona-0.9.11.jar) to method sun.nio.ch.FileChannelImpl.unmap(java.nio.MappedByteBuffer)
> WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/ckornie/.gradle/caches/modules-2/files-2.1/org.agrona/agrona/0.9.11/d539577c77df892e1efe97e7575e17f6e34c44ef/agrona-0.9.11.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
> WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/ckornie/.gradle/caches/modules-2/files-2.1/org.agrona/agrona/0.9.11/d539577c77df892e1efe97e7575e17f6e34c44ef/agrona-0.9.11.jar) to field sun.nio.ch.SelectorImpl.publicSelectedKeys

**Comment by rwilliams-r7** [comment]
any update on this?

**Comment by mjpt777** [comment]
There is currently no alternative to those with Java 10 or 11. I've seen both discussed but no good solutions have been offered.

**Comment by rwilliams-r7** [comment]
Thank you for the quick reply @mjpt777. So with what you have been posted the lib will be stuck on Java 8 for the foreseeable future?

**Comment by guidomedina** [comment]
Isn't Java 11 supposed to be a LTS release? if it is so then I believe if this still works by then we can surely ignore this for few more years, maybe we have quantum technology and these things won't matter anymore :D

**Comment by mjpt777** [comment]
Yes Java 11 is supposed to be an LTS release. I've seen discussions on how to provide alternatives to these APIs but as yet we do not have proposed solutions from the Java maintainers.

**Comment by felixbarny** [comment]
Wouldn't [`VarHandle`](https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/VarHandle.html)s be suitable as an alternative?

**Comment by mjpt777** [comment]
@felixbarny `VarHandle` does not address the specific issues from the warnings which are mostly due to unmapping `MappedByteBuffer`s. `VarHandle` can be used to replace some of the usage of `sun.misc.Unsafe` which we can look at if Java 11 gains popularity.

**Comment by mjpt777** [comment]
Closing this until the JDK has sufficient alternatives.
