### ISSUE TITLE
Int2ObjectHashMap entrySet weirdness

### ISSUE THREAD

**Issue by guidomedina** [real-logic/agrona#109]
Produces an `ArrayList` with the size of the map but with the same entry, for example:
If the map size is 100 and the elements are: `(1, 1), ..., (100, 100)`, the list will have the same element a 100 times:

`final Int2ObjectHashMap subscriptions = ....`

```
new ArrayList<>(subscriptions.entrySet()).forEach(entry -> {
  // Do something with key and value.
});
```

I had to workaround such issue by doing this:
```
new Int2ObjectHashMap<>(subscriptions).forEach((key, instrument) -> {
  // Do something with key and value.
});
```

I need to iterate over a copy which is why I was just making an `ArrayList<Map.Entry>` dumb copy.

**Comment by mjpt777** [comment]
Map entries are only valid for each step of the iteration. This allows for not allocating objects. A much better design is to stream and only capture what state you require. The Javadoc explicitly states what we are doing is valid.

https://docs.oracle.com/javase/8/docs/api/java/util/Map.Entry.html

**Comment by guidomedina** [comment]
Got it, I only reported this because I switched from `FastUtil` to `Agrona` and that part of the code broke, I never stopped to read that the actual `entrySet()` collection could be not a valid collection.

I get why `new ArrayList<>(Collection<E> collection)` is kind of unusual in itself because it tries to get an `E[]` representation of the passed collection hence this corner case.

Sorry for the false positive then.

**Comment by guidomedina** [comment]
Also, I have to thank you guys for this awesome and simplified API.
I was using `JCTools` for for non-blocking bounded and unbounded queues for Akka and `FastUtil` for primitive collections, both were extra dependencies for my project.

Because `akka-remote` depends on `aeron` which depends on `agrona` I was able to consolidate both queues and primitive collections with `agrona` which is great for me ;-)
