### ISSUE TITLE
Can JCF classes be Serializable?

### ISSUE THREAD

**Issue by guidomedina** [real-logic/agrona#110]
It is a rather odd request but another project which I switched from `FastUtil` to `Agrona` serializes lists of IDs to the DB using standard Java serialization but that can't be done if one of the objects _-`IntArrayList` in this case-_ is not `Serializable`

**Comment by mjpt777** [comment]
I've added it but wow that is a crazy thing to do! ;-) I feel dirty adding this as an enhancement.

**Comment by guidomedina** [comment]
Is only a marker interface, don't worry, everything is going to be OK.
It is a 10 years old code base so not much I can do unless I do things gradually :(

**Comment by guidomedina** [comment]
In the other hand, on the other project (Financial Industry) which is a green field project, everything is wonderful, Java serialization there is disabled, forever !!!
