### ISSUE TITLE
ObjectHashSet cached iterator blocks some HashSet replacements

### ISSUE THREAD

**Issue by nitsanw** [real-logic/agrona#115]
In an existing application I have set out to replace use of JDK HashSet with ObjectHashSet on grounds of footprint and performance. This was a large but mechanical process of find and replace and yielded a nice benefit. The one concern raised in the process is the choice made for iterator to reuse a cached instance. This not only prevents nested iteration, but also prevents concurrent iteration of pre-initialized sets (and thereafter immutable and properly published).
I understand the choice in Agrona to cache the iterator was made on grounds of reduced allocation.
Would you consider going for the standard allocating approach?

**Comment by RichardWarburton** [comment]
A proposal for the Agrona collections, made ages ago, was to expose a way of creating an iterator and have an `iterator` method that associated that iterator rather than returned one. so you would have something like:

```
HashSetIterator<String> it = new HashSetIterator<>();
hashSet.iterator(it);
while (it.hasNext()) {
 // You know the rest
```

Then you could continue with caching as the default approach but also enable nested iteration as well.

**Comment by mjpt777** [comment]
An alternative would be to provide an option to the constructor for indicating if the cached iterator or allocation should be be employed.

Happy to accept a PR on this.

**Comment by nitsanw** [comment]
@mjpt777 this is a good compromise on the API side. I'll PR later today.

**Comment by nitsanw** [comment]
Sorted! thanks for the quick turn around.
When is the next release?

**Comment by mjpt777** [comment]
Likely well do a release within a week. For consistency this change should be applied to the other sets at least.

**Comment by nitsanw** [comment]
@mjpt777 are you holding back next release wait for other sets or just not got round to it? I can help with the former if it's a blocker for you

**Comment by mjpt777** [comment]
I've done the sets but the Maps could also benefit. The collections and iterators, within maps, need separate consideration. The release is waiting on some work we need to finish up on Aeron.
