### ISSUE TITLE
Add methods to direct buffer for putting and getting numbers encoded as ASCII

### ISSUE THREAD

**Issue by mjpt777** [real-logic/agrona#117]
Natural numbers
Signed numbers
Decimal numbers

Should be implemented allocation free.

**Comment by RichardWarburton** [comment]
Artio actually already has methods for this on its AsciiBuffer. I'm happy to PR the additions if you want.

**Comment by mjpt777** [comment]
It would be good to migrate some of them. The implementations from Artio could be better optimised, e.g. single bounds check rather than byte by byte, plus a few other refinements. Artio could then use the versions in Agrona.

**Comment by RichardWarburton** [comment]
I'm just taking a look at this issue now. What are your thoughts on the correct behaviour for getting a numeric value if the ascii encoded bytes aren't with the range '0' - '9' ? For example I call getInt(4, 3) and the bytes in that range are 'abc'. At the moment I throw an Exception rather than just returning the wrong number but I wonder if that's really the responsibility of the Buffer or of the caller.

**Comment by mjpt777** [comment]
Thanks @RichardWarburton. I think it should throw a `NumberFormatException` when not containing `0-9` or `-`.

**Comment by mjpt777** [comment]
We should offer the parsing of `int` and `long`. I think methods should be named `parseIntAscii` and `parseLongAscii` to indicate they are performing a parse operation. With the other way being `putIntAscii` and `putLongAscii` respectively.

**Comment by RichardWarburton** [comment]
Cool, thanks for the feedback.

There's also the issue of floats. In Artio we have our own DecimalFloat class that is used for precise encoding of values and can be parsed/written. Is it worth bringing this into Agrona as well, or just using plain Java floats.

**Comment by mjpt777** [comment]
I think for now ints and longs are sufficient and we can decide in time how to handle decimals and floats.

**Comment by mjpt777** [comment]
Will not do floating point for now. Can be raised as a separate issue if required.
