### ISSUE TITLE
Aeron RateSubscriber hangs on shutdown

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Agrona#12]
Not sure if this should be an Aeron bug or an Agrona bug, but I suspect Agrona.

After the changes made in Agrona commit a3affdac9b45ed4e8125770cf7556272adbaedf8, the Aeron RateSubscriber sample app no longer shuts down gracefully for me.  Instead, I get these endlessly once a second:

```
timeout await for agent. Retrying...
timeout await for agent. Retrying...
timeout await for agent. Retrying...
timeout await for agent. Retrying...
timeout await for agent. Retrying...
```

If I instead use the head version of Agrona, but with the older version of AgentRunner.java swapped in, it once again appears to shut down cleanly.

**Comment by mjpt777** [comment]
Is this the RateSubscriber or the MediaDriver?

**Comment by strangelydim** [comment]
RateSubscriber. Media driver and other sample apps I've tried seem fine.

**Comment by mjpt777** [comment]
Thanks. I'll have a look tomorrow.

**Comment by mjpt777** [comment]
This was failing due to waiting on the thread joining yet it was returned back to the Executor pool. I've removed the option to create an Aeron client via an Executor.
