### ISSUE TITLE
Add ability to put and get integers/longs in hex encoded ASCII to direct buffers

### ISSUE THREAD

**Issue by mjpt777** [real-logic/agrona#122]
In addition to having added the ability to encode numbers in ASCII in direct buffers in decimal format it would be useful to have support for encoding in hexadecimal format which can be more efficient.

**Comment by tmontgomery** [comment]
There is a naive algorithm in BitUtil for hex strings from a `byte[]`. Can be made better.

I would also suggest being able to encode a `byte[]` as well. Just too useful.

**Comment by mjpt777** [comment]
Yes I'm aware of the BitUtil option. This unfortunately is not allocation free but could be easily modified to be so.
