### ISSUE TITLE
BitDefender false positive Java.Trojan.GenericGB.20264

### ISSUE THREAD

**Issue by SimonWaters** [real-logic/agrona#126]
Not a code bug, but we see various antivirus products flagging the 
0.9.5 Jarfile on Maven Central as malware.

We have disassembled the corresponding Class file with matching SHA1 hash, and the flagged class contains the RecordDescriptor.class file it purports to be.

We have reported this to BitDefender.

https://www.virustotal.com/#/file/cbb9b48f4d8b0944d4822abba3c0a30d7fed458be5aed972e030b7e64729c93c/details

**Comment by mjpt777** [comment]
Is this something we need to take action on or is it an issue for BitDefender?

**Comment by SimonWaters** [comment]
One for BitDefender. 

This seemed the best place I could find to flag it in case others see the same issue, or suddenly find the jar file is missing, or not readable for some reason.

Although we found it with a cached copy of 0.9.5 from a historic build it looks like it triggers on all versions of the jar file since including 0.9.12, unsurprising as your class definition has probably never needed to change. More than one AV product is affected, but I'm guessing the other AV products just take their signature feed from BitDefender.

**Comment by mjpt777** [comment]
Thanks for letting us know.
