### ISSUE TITLE
Is it possible to copy out the underlying bytes of the buffer?

### ISSUE THREAD

**Issue by darthninja1** [real-logic/agrona#128]
I want to defer the decoding of the bytes (encoded with SBE) so that its not done in the crit path.

I am reusing the UnsafeBuffer so I would like to persist the underlying bytes and access them at a later stage.

Any suggestions?

Thanks

**Comment by RichardWarburton** [comment]
There's a getBytes() method on UnsafeBuffer that will copy the bytes to some other container.
