### ISSUE TITLE
Question: onSpinWait only works in Java 9?

### ISSUE THREAD

**Issue by jamesbond00** [real-logic/agrona#129]
https://github.com/real-logic/agrona/blob/9cb7c57dad1025f40b3eae05df6474baa5ef1918/agrona/src/main/java/org/agrona/hints/ThreadHints.java#L64

Just a quick question. The onSpinWait method really works in Java 9 only?

**Comment by mjpt777** [comment]
Only Java 9 with the Oracle JDK. It does work on previous versions with Azul Zing JVMs.
