### ISSUE TITLE
Suggestion : continuous calls of StringBuilder.append

### ISSUE THREAD

**Issue by o0lwj0o** [real-logic/agrona#136]
Hi,
&nbsp;&nbsp;&nbsp;&nbsp;I have found some continuous calls about `StringBuilder.append(..)` in some files. For example, there are several continuous calls from line 500 to 503 in the file  https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/collections/Int2ObjectCache.java. 
```Java
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append('{');
        for (@DoNotSub int i = 0, length = values.length; i < length; i++)
        {
            final Object value = values[i];
            if (null != value)
            {
                sb.append(keys[i]);
                sb.append('=');
                sb.append(value);
                sb.append(", ");
            }
        }
        if (sb.length() > 1)
        {
            sb.setLength(sb.length() - 2);
        }
        sb.append('}');
        return sb.toString();
}
```
&nbsp;&nbsp;&nbsp;&nbsp;If it was achieved like `StringBuilder.append(..).append(..)append(..)`, it will promote its performance.

PS:

https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/collections/Int2ObjectHashMap.java | 422-425
https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/collections/Int2IntCounterMap.java | 500-503
https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/collections/Object2IntHashMap.java | 451-454
https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/collections/Int2IntHashMap.java | 531-534

**Comment by mjpt777** [comment]
This is toString and not hot code. Can you explain how chaining the methods provides better performance?

**Comment by mjpt777** [comment]
Closing due to no follow up or evidence.

**Comment by o0lwj0o** [comment]
Sorry that i forgot this issue.
https://stackoverflow.com/questions/44334233/why-is-the-stringbuilder-chaining-pattern-sb-appendx-appendy-faster-than-reg/44338950

**Comment by mjpt777** [comment]
Note  these methods have loops so normal chaining cannot apply.
