### ISSUE TITLE
ExpandableArrayBuffer has no array constructor

### ISSUE THREAD

**Issue by buko** [real-logic/agrona#139]
I'm probably missing something very obvious (sorry) but it looks like ExpandableArrayBuffer has no constructor (or static constructor method) that will simply take a byte[] array. Instead it's always necessary to create a new ExpandableArrayBuffer and then copy data into it using putBytes. 

Is there a way to create a buffer and avoid the extra copy?

**Comment by mjpt777** [comment]
If wrapping an existing array which will be fixed size then use UnsafeBuffer.
