### ISSUE TITLE
Question: why was the ErrorHandler interface defined?

### ISSUE THREAD

**Issue by karypid** [real-logic/agrona#142]
Hi,

I am wondering what the purpose of `org.agrona.ErrorHandler` is. Specifically, why it was used instead of the standard java.lang.Thread.UncaughtExceptionHandler. It does seem like unnecessary clutter to me.

**Comment by mjpt777** [comment]
No particular reason.  There is also the thread parameter on the `UncaughtExceptionHandler` which is not required in the agent usage.
