### ISSUE TITLE
Q: UnsafeBuffer.getBytes throws an exception when the limit of ByteBuffer is less than the capacity.

### ISSUE THREAD

**Issue by artyomkorzun** [real-logic/agrona#148]
The content has been copied but after that ByteBuffer.position throws an exception.

Should org.agrona.concurrent.UnsafeBuffer#getBytes(int, java.nio.ByteBuffer, int) check limit instead of capacity?

```
@Test(expected = IndexOutOfBoundsException.class)
public void shouldThrowIndexOutOfBoundsException() {
        ByteBuffer byteBuffer = ByteBuffer.allocate(4);
        byteBuffer.limit(2);

        UnsafeBuffer buffer = new UnsafeBuffer(new byte[4]);
        buffer.getBytes(0, byteBuffer, 4);
}
```

**Comment by mjpt777** [comment]
The design behind the Agrona direct buffers is to ignore position and limit as these have concurrency issues. Only capacity is taken into account.

**Comment by artyomkorzun** [comment]
Just saw that the method uses the position of the destination byte buffer so I thought the limit should have been taken into account. 

I have one more question according to bounds checks:
```
public static boolean isOutOfBounds(final int index, final int capacity) {
        return Integer.toUnsignedLong(index) >= capacity;
    }

public static boolean isOutOfBounds(final int index, final int length, final int capacity) {
       return Integer.toUnsignedLong(index) + Integer.toUnsignedLong(length) > capacity;
}
```
This code contains less branches and the compiled version is good enough. I'm not ASM expert and I'd like to hear your opinion about this. 

Thank you.

**Comment by mjpt777** [comment]
You first example would work for isOutOfBound even in the case of a negative number. The second is flawed if a negative index or length was passed in.

**Comment by artyomkorzun** [comment]
It works for negative index or length as well. Let's have a closer look.

An integer negative value has 31 high bit equal to 1.

After call Integer.toUnsignedLong any negative integer becomes a positive long value in range [Integer.MAX_VALUE + 1, 2 * Integer.MAX_VALUE + 1].

So lhs is always more than Integer.MAX_VALUE in case of negative index or/and length.

While rhs is always less or equal to Integer.MAX_VALUE.

**Comment by mjpt777** [comment]
I've benchmarked this idea against the existing approach and what you propose is a little slower. If `Integer.toUnsignedLong(int)` was an intrinsic then it may be better but as a predictable branch it is better as it is.
