### ISSUE TITLE
Impossible cast in IntHashSet

### ISSUE THREAD

**Issue by mtopolnik** [real-logic/Agrona#15]
The [`IntHashSet#toArray(T[])`](https://github.com/real-logic/Agrona/blob/master/src/main/java/uk/co/real_logic/agrona/collections/IntHashSet.java#L214) method makes an unchecked cast of an `int[]` into `T[]`, but `T` cannot possibly be `int`. This means that there is no argument which can be pased to the method and have it succeed.

I propose either throwing `UnsupportedOperationException` (if this method is not of real interest) or supplying the following impl:
```java
@SuppressWarnings("unchecked")
public <T> T[] toArray(T[] into) {
    final Class<?> aryType = into.getClass().getComponentType();
    if (!aryType.isAssignableFrom(Integer.class)) {
        throw new ClassCastException("Cannot store Integers in array of type " + aryType);
    }
    final int[] values = this.values;
    final Object[] ret = into.length >= this.size? into : (T[]) Array.newInstance(aryType, this.size);
    for (int from = 0, to = 0; from < values.length; from++) {
        final int val = values[from];
        if (val != missingValue) {
            ret[to++] = val;
        }
    }
    if (ret.length > values.length) {
        ret[values.length] = null;
    }
    return (T[]) ret;
}
```

**Comment by mjpt777** [comment]
Thanks @mtopolnik. You are right this method is an issue. I think there is also a bigger issue with the array methods. The backing array in the set is sparsely populated so the returned arrays should be smaller and the missing values need to be accounted for. Let me follow up with @RichardWarburton to come up with a suitable solution.

**Comment by mtopolnik** [comment]
Oops, that slipped past me. I've updated the code with a version which accounts for that.

**Comment by mjpt777** [comment]
The `Object[] toArray()` method also suffers from this issue.

**Comment by RichardWarburton** [comment]
Thanks for the bug report @mtopolnik.

27b6fb2ec1211fadd56103f8f8e61161ad12c8bd fixes this issue and the Object[] toArray() bug as well. I've gone for a slightly different approach which conforms to the Collection.toArray() javadoc on exceptions thrown. Let me know if there's any remaining issue.
