### ISSUE TITLE
Make ensureCapacity(...) and/or calculateExpansion(...) methods of Expandable*Buffer classes protected

### ISSUE THREAD

**Issue by l-yara** [real-logic/agrona#156]
Can we have these method protected? It will enable some additional project-specific tricks like touching callbacks when unexpected allocation happens

**Comment by mjpt777** [comment]
This would have a performance impact as the method would go from invoke static to invoke virtual. Have you considered using something like Byte Buddy to aspect the code for such features?

**Comment by l-yara** [comment]
> This would have a performance impact as the method would go from invoke special to invoke virtual.
agree for ensureCapacity() -  better to keep them private for performance indeed. What about calculateExpansion(...) - these are called only when Buffer need to grow so we do not expect them to be too fast anyway and we do not call them often?

> Have you considered using something like Byte Buddy to aspect the code for such features?
I have but it looks too much accidental complexity compared to simple method overriding. Thank you for Byte Buddy reference - never tried it before.

**Comment by mjpt777** [comment]
The agrona-agent module uses Byte Buddy for checking alignment. It is a good solution for this type of behaviour.
