### ISSUE TITLE
Bump up the minor version if the version has breaking changes

### ISSUE THREAD

**Issue by deepblueli** [real-logic/agrona#157]
Hi, 

We had an issue where Agrona 0.9.26 is not compatible with sbe 1.8.x.
Is it possible in the future if the version is having a breaking change, increase the minor version?

Another question I have is I have a project that has dependency on both Agrona and SBE (i.e. pulling in both sbe-all.jar and agrona.jar). I can see that sbe-all contains all Agrona classes , if the Agrona dependency version is different from the version embedded in sbe-all, we can have uncertainty during runtime on which Agrona class version it loads depends on classpath order (especially if we use "*" as classpath).
Do you think that sbe should have an alternative without embedding all shadow dependencies in its jar, and explicitly declare its dependency in pom? That'll prevent having duplicate classes in classpath

Thanks.

**Comment by mjpt777** [comment]
Yes you are right that we should have be more explicit about the change. We have been more relaxed with this project as it is pre 1.0. Going forward we likely start from 1.0 soon.

I've updated SBE to declare pom dependencies with this commit https://github.com/real-logic/simple-binary-encoding/commit/4f9184744020ec38d3aaca557da415234ac869b1. This is a new feature for Gradle and becomes the default in 5.0. Hopefully this helps.

**Comment by deepblueli** [comment]
Thanks Martin! What's the reason that sbe has Agrona classes embedded in its jar?

**Comment by mjpt777** [comment]
SBE makes use of things like the direct buffers from Agrona and standard interfaces for the generated codecs. The Agrona direct buffers are used in many projects now for example as they make dealing with ByteBuffer much more reasonable.
