### ISSUE TITLE
Possible bug in ManyToOneRingBuffer#unblock

### ISSUE THREAD

**Issue by honzatran** [real-logic/agrona#159]
Hi, 

I am using the many to one ring buffer in one of our projects, and I encountered an issue in the unblock method. 

It seems to me that the method returns false when the ring buffer is full, cause of the first _if_ in unblock. As a consequence, write to the ring buffer fails since it is full, and we cannot read any elements from it due to the corruption.

Here is the unit test to reproduce.

`
public class AgronaBufferTests {

    private static final int CAPACITY = 16 * 1024 * 1024;
    private static final int TOTAL_BUFFER_CAPACITY = CAPACITY + RingBufferDescriptor.TRAILER_LENGTH;

    private static final int TOTAL_BUFFER_LENGTH = CAPACITY + RingBufferDescriptor.TRAILER_LENGTH;
    private static final int TAIL_COUNTER_INDEX = CAPACITY + RingBufferDescriptor.TAIL_POSITION_OFFSET;
    private static final int HEAD_COUNTER_INDEX = CAPACITY + RingBufferDescriptor.HEAD_POSITION_OFFSET;
    private static final int HEAD_COUNTER_CACHE_INDEX = CAPACITY + RingBufferDescriptor.HEAD_CACHE_POSITION_OFFSET;

    private UnsafeBuffer buffer;
    private ManyToOneRingBuffer ringBuffer;

    @Before
    public void createBuffer() {
        buffer = mock(UnsafeBuffer.class);

        when(buffer.capacity()).thenReturn(TOTAL_BUFFER_CAPACITY);

        this.ringBuffer = new ManyToOneRingBuffer(buffer);
    }

    @Test
    public void shouldUnblockWhenFull() {
        // ring buffer is full
        when(buffer.getLongVolatile(HEAD_COUNTER_INDEX)).thenReturn(180L);
        when(buffer.getLongVolatile(HEAD_COUNTER_CACHE_INDEX)).thenReturn(180L);
        when(buffer.getLongVolatile(TAIL_COUNTER_INDEX)).thenReturn(180L + CAPACITY);

        when(buffer.getIntVolatile(180)).thenReturn(0);

        final UnsafeBuffer unsafeBuffer = new UnsafeBuffer(ByteBuffer.allocateDirect(20));

        final int read = ringBuffer.read((msgTypeId, buffer, index, length) -> {

        });

        // we can't read any item from the ring buffer since it is corrupted
        assertEquals(0, read);

        // ring buffer is full
        assertFalse(ringBuffer.write(1, unsafeBuffer, 0, 20));

        // unblock does not fix the corruption. this assert fails
        assertTrue(ringBuffer.unblock());

        final int readAfterUnblock = ringBuffer.read((msgTypeId, buffer, index, length) -> {

        });

        // we can't read any item from the ring buffer since it is corrupted
        assertTrue(readAfterUnblock > 0);
    }
}
`

Could you please have a look at it ?

Thank you,
Hiep

**Comment by mjpt777** [comment]
This test does not make sense to me. Unblock is designed for when another process dies part way through writing a message by making the message as a gap and thus allowing readers to skip over it. It does not fix some other thread deliberately corrupting the buffer.

Anyway, unblock needs to modify the underlying buffer and all you have in your test is a mock that does not respond to the unblock actions.

**Comment by honzatran** [comment]
Sorry, I was a little bit busy, but I will try to add put a better unit test as soon as possible.
