### ISSUE TITLE
Long2LongHashMap.keySet().iterator().next() returns self

### ISSUE THREAD

**Issue by mtopolnik** [real-logic/agrona#16]
FindBugs has a dedicated check for this pattern because it was employed in OpenJDK and emulated in many other places (it has already been fixed in OpenJDK). The trick which saves from emitting garbage also breaks code such as `new ArrayList<>(map.entrySet())`. AFAIK Java 8 has significantly improved Escape Analysis so a safe implementation should still be garbage-free in most usages.

https://github.com/real-logic/Agrona/blob/master/src/main/java/uk/co/real_logic/agrona/collections/Long2LongHashMap.java#L470

https://github.com/real-logic/Agrona/blob/master/src/main/java/uk/co/real_logic/agrona/collections/Long2ObjectHashMap.java#L693

**Comment by mtopolnik** [comment]
Just to contribute an idea how I solved it in our backport of Agrona:
```java
protected AbstractIterator(final int firstIndex) {
    this.firstIndex = firstIndex;
    index = firstIndex - 2;
}

public boolean hasNext() {
    boolean beforeFirst = index < 0;
    while (beforeFirst || entries[index] == missingValue) {
        nextIndex();
        if (index == firstIndex && !beforeFirst) {
            return false;
        }
        beforeFirst = false;
    }
    return true;
}
```

```java
EntryIterator reset() {
    index = firstIndex - 2;
    return this;
}

(import java.util.AbstractMap.SimpleImmutableEntry;)

public Entry<Long, Long> next() {
    if (!hasNext()) {
        throw new NoSuchElementException();
    }
    final Entry<Long, Long> ret = new SimpleImmutableEntry<Long, Long>(entries[index], entries[index + 1]);
    nextIndex();
    return ret;
}
```

**Comment by RichardWarburton** [comment]
Thanks for the bug report @mtopolnik.

Can you provide a realistic benchmark which supports the claim that it should be garbage-free. It looks to me like you immediately have to return the allocated object, so it would immediately escape the next() method unless its inline. I'm sure that's reproducible in a micro-benchmark, but should we really be relying on inlining here?

It would be good to have your thoughts here @mjpt777. At the moment we're technically not allocation Free on the entry-set case, but entry-set is really more implemented for completeness with the assumption that it won't be used on performance critical paths. We could:

a. just fix this bug and not worry about the allocation implication
b. leave things as is - low allocation, but not make things worse.
c. genuinely determine people care about the entryset, make it properly allocation-free and not fix this bug.

If any changes are being made, I'd like to port this over to be an Int2IntHashMap and then use the primitive expander stuff to create the Long2Long version so there's less need for duplicate maintenance in future.

**Comment by mtopolnik** [comment]
Yes, without inlining it can't be garbage-free. Personally I would be OK with the allocation-free approach, but the doc should then clearly state in what way the general contract is violated.

**Comment by RichardWarburton** [comment]
Good point. I'll update the docs either way when a decision is made.

**Comment by mtopolnik** [comment]
However, regardless of that decision the impl could be improved such that invoking `next` without prior `hasNext` works. The price in my impl is just the calculation of `index < 0` and the involvement of this check in existing branch points.

**Comment by mjpt777** [comment]
@mtopolnik Are you (Hazelcast) updating the copyright to show the origin and give credit for the work when you backport? It is an Apache 2.0 licence.

**Comment by mtopolnik** [comment]
We change the copyright to ours and include a statement in `NOTICE`. Should the copyright in the file also include this? Do we need two lines of copyright for the backport? I tried to find what is the proper procedure, but I'm unsure on this point.

**Comment by mjpt777** [comment]
You cannot take the copyright to work that is already under copyright. You have the right to use it under an Apache 2.0 licence but the copyright still resides with Real Logic in this case.

**Comment by mtopolnik** [comment]
But since there have been many changes to the code, it is truly derivative work. Who holds the copyright for the changes? Does it always stay with Real Logic, regardless of the magnitude of changes?

**Comment by mjpt777** [comment]
I think on that you need the advice of a lawyer.

**Comment by RichardWarburton** [comment]
@mtopolnik an alternative that might work for you is to depend on the versions in Agrona, rather than copying and maintaining a copy. If you don't want to require your clients explicitly depend upon the agrona library then you can use the maven shade plugin to copy in the dependency to your final build jar in your build pipeline.

**Comment by mjpt777** [comment]
@RichardWarburton I think the issue with an explicit dependency is that they require Java 6.

**Comment by mtopolnik** [comment]
Yes, that's how it all started... I would of course be much happier with an outside dependency which maintains itself. My current solution is to have both lines of copyright statement in each file, plus the attribution in `NOTICE`. In any case, Real Logic's copyright is in no way influenced by the statements in the files, they just make the rights more visible and explicit.

**Comment by mjpt777** [comment]
@mtopolnik My legal person point out the clauses in the Apache 2.0 licence regarding attribution.

1. You must cause any modified files to carry prominent notices stating that You changed the files; and
2. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
3. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file

**Comment by mjpt777** [comment]
The spec for [Map.Entry](https://docs.oracle.com/javase/7/docs/api/java/util/Map.Entry.html) says the entries need only be valid for duration of the iteration.
