### ISSUE TITLE
Possible bug in ManyToOneRingBuffer#unblock, better unit test

### ISSUE THREAD

**Issue by honzatran** [real-logic/agrona#160]
Ok, sorry for the previous issue #159, 

So basically, the issue is in my opinion, that the unblock does not work as it should when the ring buffer is full, here is a unit test which can be added to the org.agrona.concurrent.ringbuffer.ManyToOneRingBufferTest. This test should hopefully reproduce the issue.

```java  
    public void shouldUnblockGapWithZerosWhenRingBufferIsFull()
    {
        final int messageLength = ALIGNMENT * 4;
        when(buffer.getLongVolatile(HEAD_COUNTER_INDEX)).thenReturn((long)messageLength);
        when(buffer.getLongVolatile(TAIL_COUNTER_INDEX)).thenReturn((long)messageLength + CAPACITY);

        when(buffer.getIntVolatile(messageLength * 2)).thenReturn(messageLength);

        assertTrue(ringBuffer.unblock());

        final InOrder inOrder = inOrder(buffer);
        inOrder.verify(buffer).putInt(typeOffset(messageLength), PADDING_MSG_TYPE_ID);
        inOrder.verify(buffer).putIntOrdered(lengthOffset(messageLength), messageLength);
    }
```

I just took the unit test org.agrona.concurrent.ringbuffer.ManyToOneRingBufferTest#shouldUnblockGapWithZeros and set the mock so it returns on getLongVolatile(TAIL_COUNTER_INDEX) messageLength + CAPACITY which should mean that the ring buffer is full. 

I hope this unit test is clearer, than the one from previous issue. 

Just to elaborate on the issue, we use the ManyToOneRingBuffer, and its underlying buffer is mmap from a file. What we experienced is that the underlying file get corrupted and at the same time the ring buffer was full. I restarted our system, but the buffer was block on the next start and invoking the unblock method didn't help.

**Comment by mjpt777** [comment]
Added some tests and a fix. Thanks this is a better report.

**Comment by honzatran** [comment]
Thanks for quickly fixing this. I will close the issue.
