### ISSUE TITLE
Asserting aligned non-plain access

### ISSUE THREAD

**Issue by brianfromoregon** [real-logic/agrona#165]
Quote from http://openjdk.java.net/jeps/193
"In the case of unaligned access all but the plain access mode methods will throw IllegalStateException."

Have you considered having UnsafeBuffer also check/throw for naturally aligned accesses for the ordered,volatile,CAS operations? If VarHandle is doing it, I suppose it'd make sense here too.

**Comment by brianfromoregon** [comment]
Thanks for the pointer Martin, was not aware of the agent! 
Do you have a link to docs saying straddling accesses are atomic on x86? The docs I read say otherwise but perhaps they are outdated.

Quote from https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-vol-3a-part-1-manual.html
```
the following additional memory operation will always be carried out atomically:
  * Unaligned 16-, 32-, and 64-bit accesses to cached memory that fit within a cache line

Accesses to cacheable memory that are split across cache lines and page boundaries are not guaranteed to be atomic
```

**Comment by mjpt777** [comment]
Section 8.1.1. that you reference is for memory operations that do not include the LOCK prefix. When LOCK instructions are used then see 8.1.2.2:

> The integrity of a bus lock is not affected by the alignment of the memory field. The LOCK semantics are followed for as many bus cycles as necessary to update the entire operand. However, it is recommend that locked accesses be aligned on their natural boundaries for better system performance:

Now the JVM may not implement some of these semantics with a LOCK instruction, e.g. volatile could be done with LOCK XCHG but it is typically not. For CAS it is and C++ 11 typically does for sequential consistent writes. So ordered and volatile could be an issue depending on how the JVM implements those.

Best to know your data layout and test. Always relying on runtime checks is one approach but can be the one with the performance hit when other approaches can avoid it. A combination of static analysis and runtime debug build are often a good approach.

**Comment by brianfromoregon** [comment]
Good points. 
I feel you struck a nice balance with optional bounds checking via a system property toggle. I think another property for alignment checking could make sense, my experience is system properties tend to be simpler and less scary to toggle in corporate environments than adding agents. But you may find the agent is the better fit for this.
I think oracle and azul do not issue LOCK instructions for ordered,volatile on x86 today.
Thanks for the chat, take care!
