### ISSUE TITLE
MappedResizableBuffer for read-only files

### ISSUE THREAD

**Issue by darthninja1** [real-logic/agrona#168]
The IoUtil.map call assumes you have r/w access to the file. I have a usecase where I need to mmap a read-only file generated by a different process. Could you add support for read-only files?

I locally modified the below line in MappedResizableBuffer and it seems to work fine now  -

`        addressOffset = IoUtil.map(fileChannel, FileChannel.MapMode.READ_ONLY, offset, length);
`

**Comment by mjpt777** [comment]
Why do you need a resizable buffer if read only? Why not do a normally mapping and wrap with UnsafeBuffer?

**Comment by darthninja1** [comment]
Because UnsafeBuffer takes integer offsets (afaik). I have to mmap a file > 2GB. And I want to avoid re-wrapping different sections of the file.
