### ISSUE TITLE
IoUtil mapNewFile does not correctly fill the file with zeros

### ISSUE THREAD

**Issue by fkettwig** [real-logic/agrona#172]
`org.agrona.IoUtil.mapNewFile` places a single zero every `BLOCK_SIZE` instead of filling the file.

When `fillWithZeros` is `true`, only part of the file has zeros:

```ruby
if (fillWithZeros)
{
	int pos = 0;
	while (pos < length)
	{
		mappedByteBuffer.put(pos, (byte)0);
		pos += BLOCK_SIZE;
	}
}
```

Is adding a single zero byte at `pos` but incrementing it by `BLOCK_SIZE` .

**Comment by mjpt777** [comment]
This is how sparse files work.
