### ISSUE TITLE
Extend Collections

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#18]
Wondering if you can expand the collections to be able to use as a generic library.

**Comment by mjpt777** [comment]
Can you be more specific about the expansion?

**Comment by sirinath** [comment]
Make it comprehensive like: FastUtil, Trove, Koloboke, etc.

**Comment by mjpt777** [comment]
Sorry but this is not the intention of Agrona. 

Via Agrona we are making available common utilities that we think might be useful as a by product of developing other projects such as Aeron. The goal is not to produce a comprehensive generic library. Others are doing that.
