### ISSUE TITLE
IntArrayList.equals forces unnecessary boxing of its own members

### ISSUE THREAD

**Issue by gregallen** [real-logic/agrona#180]
Comparing with another List (not an IntArrayList) forces boxing of all members

```
for (final Object o : that)
                {
                    if (o == null || o instanceof Integer)
                    {
                        final Integer thisValue = get(i++);
```

could be re-written, without get() and keeping nullValue handling, comparing the primitive ints

**Comment by mjpt777** [comment]
Feel free to send a patch.

**Comment by mjpt777** [comment]
Closing due to no follow up.
