### ISSUE TITLE
Why doesn't IntArrayList allow wrapping for int array less than 10 elements?

### ISSUE THREAD

**Issue by happy15** [real-logic/agrona#182]
Hi there,

I am new to agrona and tried to feel the usage of IntArrayList. Below is what I tried:
```
int[] a = new int[]{1,2,3};
IntArrayList ial = new IntArrayList();
ial.wrap(a, a.length);
```
Of cause this code complains about `illegal initial array length 3, minimum required is 10`.

I read the code and I can see how this happens. What I don't understand are:

1. why do I need to provide initial size to wrap an existing int array? since it can be figured out by `a.length`.
2. why can't I wrap a int array less than 10 elements? since IMHO the requirements to capacity are to be big enough to contain the data and to auto increase/decrease on demand. 

Anything I missed here? Looking forward to the rationale.

**Comment by mjpt777** [comment]
It was a pragmatic lower bound and having to deal with a special case of a zero length array when resizing. It is all that was required for our use. I've made it more flexible with the latest change.

**Comment by happy15** [comment]
Good to know and thanks for the reply.
