### ISSUE TITLE
HighResolutionClock / SystemEpochNanoClock do not return nanosecond precision values by default

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/agrona#186]
I would expect `SystemEpochNanoClock.nanoTime()` and `HighResolutionClock.epochNanos()` to return nanosecond precision values.  `SystemEpochNanoClock.nanoTime()` delegates to `HighResolutionClock.epochNanos()`, so they both return the same value. In practice they return millisecond precision values formatted as nanoseconds by default.

For example, if I run:

```
while (true)
        {
            Thread.sleep(100);
            SystemEpochNanoClock clock = new SystemEpochNanoClock();
            System.out.println(clock.nanoTime());
        }
```

I get output like:

```1571145442682000000
1571145442782000000
1571145442882000000
1571145442982000000
1571145443082000000
1571145443182000000
1571145443283000000
1571145443383000000
1571145443483000000
1571145443583000000
1571145443683000000
1571145443783000000
1571145443884000000
1571145443984000000
```

At the very least the javadoc here should be clarified I think. If you look at the implementation of `Instant.now()` which you're using in `HighResolutionClock.epochNanos()` it ultimately backs onto `System.currentTimeMillis()`. So it's a monotonic time source, but not nanosecond precision.

**Comment by mjpt777** [comment]
Are you running on Java 8 or 11?

See https://stackoverflow.com/questions/33477695/why-does-the-new-java-8-date-time-api-not-have-nanosecond-precision/33478391#33478391

**Comment by RichardWarburton** [comment]
Thanks for clarifying. I was originally testing on Java 8, on Java 11 I do get microsecond level precision when running on linux.

I do think that the Javadoc for this method should clarify that under Java 8 you will only get millisecond precision and even on 9+ you may still not really get nanosecond.

**Comment by mjpt777** [comment]
It is JVM dependent. Zing is another story again. I'll add a note the actual precision/resolution is JVM dependent.
