### ISSUE TITLE
Endless Loop in Int2IntHashMap.get(),  uk.co.real-logic:Agrona:0.4.2

### ISSUE THREAD

**Issue by bobymicroby** [real-logic/Agrona#20]
Hello @RichardWarburton 

I wanted to use the map for a bounded in size cache. I've set the capacity to be pow of 2 and the loading factor to 1, because I don't want to trigger a resize operation.

Unfortunately when the loading factor is >= 1 there is a endless loop in get.

```java
 @Test
    public void testSanity() throws Exception
    {

        Long2LongHashMap map = new Long2LongHashMap(4, 1, 0);
        map.put(1, 1);
        map.put(2, 1);
        map.put(3, 1);
        map.put(4, 1);

        map.get(5);

    }
```

**Comment by RichardWarburton** [comment]
Hi @bobymicroby,

Thanks for your bug report. I've added validation to make sure that load factors are always < 1.0 to resolve the infinite loop.

I appreciate this probably isn't what you want - you probably want a hashmap that doesn't resize. I think that's probably a different data structure and I don't necessarily want to make this one class fit two different use cases. What do you think @mjpt777?

If someone wants to pull request a primitive-primitive hashmap implementation that is fixed size then I would be happy to review/accept that.

**Comment by mjpt777** [comment]
I agree that `loadFactor` should be limited to < 1.0. In fact I'd recommend you keep it to < 0.7 if you want to avoid cluster chains.

A bounded cache is a useful thing that can be implemented with an open addressing hash map that does an LRU replacement on the cluster chain when the loadFactor is reached. This can be nicely combined with a variant on cuckoo hashing.

It is something I've considered adding to Agrona but am not likely to get time for a couple of months.

**Comment by bobymicroby** [comment]
@RichardWarburton I think you are right. It's a bit different data structure. the "put" method should be replaced by "offer" that will return true or false if the map is full and you are trying to offer a key that wasn't previously in the map. I can probably create something like Int2IntFixedHashMap, reuse 90% percent of the current implementation,get rid of resize/rehash, throw unsupported operation for puts..but  I am afraid that this will get messy. I don't  think I will be able to write the LRU map that Martin offered. The fixed size primitive-primitive hashmap implementation  will be semantically different from Map, because it will not be able to implement the "put" method correctly. Do you think that such a data structure should have the right to exist, or we should cast this issue to the void ?

**Comment by bobymicroby** [comment]
I'm closing the issue. And by the way, you have a typo in the IAE you introduced :)

**Comment by mjpt777** [comment]
Thanks
