### ISSUE TITLE
BusySpinIdleStrategy.pause static method for Java

### ISSUE THREAD

**Issue by agritsiuk** [real-logic/agrona#204]
Hello,

it would be great to have a static method in Java BusySpinIdleStrategy.pause()
like in CPP version.

Thank you in advance!

**Comment by tmontgomery** [comment]
The `IdleStrategy` interface doesn't allow this cleanly. However, you can do a couple things.
```
BusySpinIdleStrategy.INSTANCE.idle();
```
or directly (for access to PAUSE if available)
```
ThreadHints.onSpinWait();
```

**Comment by agritsiuk** [comment]
Thank you Todd, we'll use onSpinWait.
