### ISSUE TITLE
one2one ringbuffer c<->java issues

### ISSUE THREAD

**Issue by nevgeniev** [real-logic/agrona#207]
hi guys,

it looks like one2one ringbuffer is implemented differently in c vs java. (sorry didn't dig deep into that issue yet). but in my case with writer in C and reader in java, reader gets ahead of writer easily... both reader and writer in c seems to be ok. also replacing ringbuffer implementation with many2one fixes issue instantly

**Comment by mikeb01** [comment]
Do you have a test case that you could share?

**Comment by nevgeniev** [comment]
it works! :) @tmontgomery can you verify (just in case) that many2one is in sync with java version?

**Comment by tmontgomery** [comment]
Many2One is used a lot with Aeron for C++ and Java. It gets a good workout with the tests involved. That and it looks to be in sync anyway.
