### ISSUE TITLE
Int2IntHashmap incorrect size() after rehash

### ISSUE THREAD

**Issue by bobymicroby** [real-logic/Agrona#21]
```java

   @Test
    public void correctSizeAfterRehash() throws Exception
    {

        Long2LongHashMap map = new Long2LongHashMap(16, 0.6D, -1);

        IntStream.range(1, 17).forEach(i -> map.put(i, i));

        assertEquals(16, map.size());
        ArrayList<Long> keys = new ArrayList<>();

        map.forEach((k, v) -> keys.add(k));

        keys.forEach(map::remove);

        assertTrue(map.isEmpty());
    }
```

P.S There is still typo in the IAE in the constructor.

```java

if (loadFactor >= 1.0)
        {
            throw new IllegalArgumentException("Load factor must be <= 1.0");
        }

```

Since you are asserting for >= , the message should state < only

**Comment by RichardWarburton** [comment]
Hmm, I've just added and committed this testcase for the Int2IntHashMap and it passes fine. Perhaps I've misread something, but I'm closing this issue for now. If there's a testcase that fails feel free to re-open the issue.

**Comment by bobymicroby** [comment]
@RichardWarburton  I suggest you check your code generator then.

![image](https://cloud.githubusercontent.com/assets/927575/9443353/5215f010-4a89-11e5-87d7-20fbf948b3d5.png)


![image](https://cloud.githubusercontent.com/assets/927575/9443368/60b1c194-4a89-11e5-9740-38e5484d14cb.png)

**Comment by RichardWarburton** [comment]
I've just run this exact same test against agrona head and it passes fine. So I conclude that its already been fixed in the current snapshot. There should be a new release out soon.

**Comment by bobymicroby** [comment]
Do you have a snapshots repo somewhere ?

**Comment by RichardWarburton** [comment]
We don't publish snapshots anywhere at the moment I don't think.

**Comment by bobymicroby** [comment]
I've build the snapshot and it's working locally. :+1:
