### ISSUE TITLE
Corrupted ManyToOneRingBuffer

### ISSUE THREAD

**Issue by postulka** [real-logic/Agrona#22]
Hi,

we are using Agrona in our project, specifically ManyToOneRingBuffer and today we encountered an issue which we don't know how it could happen.

We are writing into the buffer from multiple threads and reading the data from single thread. At one point the reader thread got stuck at .waitForMsgLengthVolatile(ManyToOneRingBuffer.java:312) inside of read method and it is not possible to read the data from buffer anymore.

Environment:
agrona version: 0.3.1
the size of the buffer is set to:  16777216
when we debug the read method on a given buffer we see the following:
record index:  16777208
tail: 184549360
head: 167772152
msgType on a given index: -1
msgLength: 0

We see that in version 0.4.3 which we use in trunk the read method is different (specifically the while loop was removed and replaced with break). Do you know whether there was some bug in version 0.3.1 which could cause the "corrupted" buffer we are seeing?

Please let us know in case you want us to upload the buffer somewhere - we are happy to do it.

Thank you.

Petr

**Comment by mjpt777** [comment]
The old version had a bug with insufficient space remaining to write in a header. This was fixed in commit 205dea24d7dd9d7d00450539c5dee67e04d33a43.

**Comment by postulka** [comment]
Thanks for the confirmation Martin ... we will upgrade to the latest version then.
