### ISSUE TITLE
Add version of org.agrona.SystemUtil#loadPropertiesFile that can preserve existing values

### ISSUE THREAD

**Issue by vyazelenko** [real-logic/agrona#226]
Utility methods [SystemUtil#loadPropertiesFile](https://github.com/real-logic/agrona/blob/c3e2072a646bec7fe4531be0d08e17b1543cee9b/agrona/src/main/java/org/agrona/SystemUtil.java#L203) and [SystemUtil#loadPropertiesFiles](https://github.com/real-logic/agrona/blob/c3e2072a646bec7fe4531be0d08e17b1543cee9b/agrona/src/main/java/org/agrona/SystemUtil.java#L249) work by overwriting system properties with the values from the given file(s). That makes sense especially when multiple files are used since the later files overwrite values of the previous files.

However this behavior is surprising for people come from frameworks such as Spring. In Spring for example explicitly set system property takes precedence over values in the property files. So the following is working with Spring but not with Agrona:
```
java -cp ... -Dmy.prop=IMPORTANT MyApp default.properties
```
With Spring value of `my.prop` will be **`IMPORTANT`** but with Agrona it will be **`DEFAULT`** (i.e. value from the `default.properties` file).

Therefore we should probably consider providing a version that can preserve property value if it is already set. One interesting question is how to do `SystemUtil#loadPropertiesFilesPreserveExisting`. We want to honor already set property when the method was called but if one is not set it should behave the same as the original `SystemUtil#loadPropertiesFiles`, i.e. next file should overwrite previous file values in the list.

**Comment by mjpt777** [comment]
We could provide an override of the `loadPropertiesFiles` method that takes an enum as the first argument. The enum can specify which priority is applied. The existing method can stay with it defaulting to one of the enum values.
