### ISSUE TITLE
Java Byte Order is Big Endian

### ISSUE THREAD

**Issue by sirinath** [real-logic/agrona#232]
Java byte order is big endian, so I am not sure if this is right:
```java
if (NATIVE_BYTE_ORDER != byteOrder)
{
       bits = Long.reverseBytes(bits);
 }
```

If the byte order is little endian only this needs to be reversed regardless of the native order.

**Comment by mjpt777** [comment]
The byte order of native buffers is platform specific.

https://docs.oracle.com/javase/8/docs/api/java/nio/ByteOrder.html#nativeOrder--
