### ISSUE TITLE
MutableDirectBuffer methods to put string could accept CharSequence

### ISSUE THREAD

**Issue by tkowalcz** [real-logic/agrona#238]
### What is the code change?

Currently methods on `MutableDirectBuffer` that treat `String` as ASCII strings accept `java.lang.String`. I encountered a case where this is a limitation and wanted to bring it up for some feedback. Methods in question:

```java
int putStringAscii(int index, String value);
int putStringAscii(int index, String value, ByteOrder byteOrder);
int putStringWithoutLengthAscii(int index, String value);
int putStringWithoutLengthAscii(int index, String value, int valueOffset, int length);
```

### Rationale

In environment where buffers and objects are reused to not allocate anything it seems reasonable to me to use `CharSequence` instead of `String` whenever possible. 

I am dealing with Log4j2 internal API that is written to not allocate objects and I need to pass (reusable) `StringBuilder` to it. Then I would like to serialise it to the Agrona ring buffer (via `ExpandableArrayBuffer`). 

### Implementation

Changing the API of `MutableDirectBuffer` and all implementations "just work" and the project compiles and all tests pass. Nevertheless this change is in a core class and it does not appear to be a binary compatible change.

**Comment by mjpt777** [comment]
This change would have a performance impact. Fetching each character would be an invoke interface operation.

**Comment by tkowalcz** [comment]
I remembered that CHA for interfaces was somehow fixed, but now rereading bugs in OpenJDK Jira I see that this is no the case. Pity. Anyway, thanks for your time.

**Comment by RichardWarburton** [comment]
If it's important then you could add an overload and have one version of the method for the String, one for the CharSequence. Then anyone using Strings would get the benefit of the more specific method and there's still a more general alterntive.

**Comment by tkowalcz** [comment]
To me it seems that in environment with low allocation one would reuse buffers and not have Strings that can be passed to that API. I can manage my use case and just copy and modify `ExpandableArrayBuffer`. 

If there is interest in a particular solution I can prototype it and provide a PR for experimentation.

**Comment by mjpt777** [comment]
We would accept a PR with the overloaded methods added on the `MutableDirectBuffer` interface with appropriate implementations.
