### ISSUE TITLE
put operation on Long2ObjectHashMap will run into infinite loop if the loadFactor is 1

### ISSUE THREAD

**Issue by kirtiteja** [real-logic/Agrona#24]
resizeThreshold = capacity * loadFactor and  the datastructure is resized when size > resizeThreshold.
So when the capacity has reached, the values array will be full and the loop in put method will run infinitely.

We may conservatively set resizeThreshold to (capacity  * loadFactor) - 1 or change the resize condition to size >= resizeThreshold.

**Comment by mjpt777** [comment]
What version are you using? This was fixed with issue #21.

**Comment by kirtiteja** [comment]
I was using 0.4.2. Just upgraded to 0.4.3.
Will close this bug.
