### ISSUE TITLE
Efficient compute / computeIfAbsent / computeIfPresent in maps

### ISSUE THREAD

**Issue by m-anthony** [real-logic/agrona#258]
Currently agrona maps use the default java.util.Map implementation of computeXXX methods which may involve doing several lookup in the map. Implementations specialized for int/long values have a custom computeIfAbsent that basically avoid Integer/Long allocations, but still does up to 2 lookups.

Would you accept a PR that creates dedicated implementations of computeXXX methods (and modifies existing primitive specializations of computeIfAbsent) so that retreiving the index of the entry to get/modify/remove is done only once ?

**Comment by mjpt777** [comment]
Yes we would consider a PR on this.

**Comment by m-anthony** [comment]
I will provide a PR soon.

However I found a little consistency issue with Int2NullableObjectHashMap and the current primitive computeIfAbsent : if a key is mapped to null, calling the default JDK computeIfAbsent(Integer, Function<Integer, ? extends V>) will compute a new mapping, however calling agrona computeIfAbsent(int, IntFunction<? extends V>)  will not compute a new mapping, and it returns null.

Should I change this behavior so that both methods match the JDK semantics in my PR ?

**Comment by vyazelenko** [comment]
Fixed by #259
