### ISSUE TITLE
UnsafeBuffer - Ability to wrap around other primitive array types 

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#26]
Is there a possibility to add the ability to wrap around other primitive array types?

**Comment by RichardWarburton** [comment]
Hi,

Thanks for your enquiry. What is the motivating use case?

**Comment by sirinath** [comment]
1. Faster array element access
2. Reinterpret bit orders

**Comment by sirinath** [comment]
Let me know if you need more info.

**Comment by mjpt777** [comment]
Yes this would be possible. It would require many more constructors and wrap methods.

It also has the implication that people could easily end up using it on unaligned data which could be unsafe in a concurrent context.

I've personally not seen a real world need for such. Even given the examples above. I'd be interested to hear if how often you seen the need on real projects and if others have that need?

**Comment by mjpt777** [comment]
This would also require a move to long based indexes and lengths which I'm not sure is worth the added complexity.

**Comment by sirinath** [comment]
This is very much needed when you cross API boundaries. You cannot pass around a byte array when you need an int array, but nevertheless you can use UnsafeBuffer in your private case.

**Comment by mjpt777** [comment]
Can you provide a concrete example? Why not just use the int array if you are dealing with ints?

**Comment by sirinath** [comment]
That's the point. If I get and int array from an API call and I want to treat this as an UnsafeBuffer there is not way to wrap it and use it. Conversely if I create a byte array to wrap around UnsafeBuffer I cannot pass it to an API which expects an int array.

**Comment by mjpt777** [comment]
We may support this in the future if others request it. In the short term feel free to fork and send a pull request. I prefer to keep API surface area to a minimum as things can be added given sufficient need but it is much harder to take thing away that may turn out to not be commonly needed, plus additional methods add complexity.

**Comment by mjpt777** [comment]
BTW Unsafe access is not necessarily faster than normal array access. Often it can be slower due to the data dependent loads following the references to the unsafe buffers. Bounds checks are often eliminated by the JIT compiler and even when applied are still fast due to CPU branch prediction.

**Comment by sirinath** [comment]
Following presentation says it is: http://www.slideshare.net/leventov/optimizing-arraybased-data-structures-to-the-limit

**Comment by mjpt777** [comment]
Did you check to code to see if Unsafe was used directly or via a wrapper like UnsafeBuffer? With UnsafeBuffer you take an indirection via a reference.

**Comment by mjpt777** [comment]
We are not going to implement this for now as it would require a move to long indexes.
