### ISSUE TITLE
Int2ObjectCache get returns unmatched item

### ISSUE THREAD

**Issue by dmtsyganov** [real-logic/agrona#262]
Int2ObjectCache.java  method get returns unmatched value!
Please take a look at line #246 - the value is assigned and will be returned from the get method even if the key don't match.
this change was introduced in v 1.16.0
It is probably critical, also, please check other collections with similar code

**Comment by vyazelenko** [comment]
@dmtsyganov Thanks for the report. It is indeed a regression in 1.16.0 which we are going to fix.

It only happens if for a key/hash an entire set is filled but none match the given key.

**Comment by vyazelenko** [comment]
Fixed with https://github.com/real-logic/agrona/commit/87efa5a80aeba09d3fd4d6640c46a9d5cc3bc0b1.

**Comment by dmtsyganov** [comment]
Thank you for fixing it so quick! Will there be a new version release, or is it fixed under the current version?

**Comment by mjpt777** [comment]
No immediate plans for a release. If you are on commercial Aeron support then use your support contact to discuss scheduling a release.

**Comment by dmtsyganov** [comment]
Got it, thank you, Martin!

**Comment by Bzil** [comment]
@vyazelenko do you know when a release date is planned?  When we increase the version we encountered this bug
