### ISSUE TITLE
Overloads to add sub strings to UnsafeBuffer

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#27]
Is it possible to add overloads to add sub strings to unsafe buffer?

**Comment by mjpt777** [comment]
Can you provide an API and usage example?

**Comment by sirinath** [comment]
```
public int putStringUtf8(final int offset, final int length, final String value, final ByteOrder byteOrder, final int maxEncodedSize)

public int putStringWithoutLengthUtf8(final int offset, final int length, final String value, final ByteOrder byteOrder)
```

**Comment by mjpt777** [comment]
Given char encoding it is just as efficient to do a sub string before calling as it would be to do internally. I'd prefer not to add these method as they might lead users to think we have a more efficient implementation which we would not have.
