### ISSUE TITLE
BUG: ShutdownSignalBarrier causes Java runtime shutdown hooks to not run

### ISSUE THREAD

**Issue by Guardian-Development** [real-logic/agrona#270]
Description:

When the ShutdownSignalBarrier class is loaded, its static initialiser overrides the default JVM Signal handler. This means on shutdown of the JVM, when the SIGTERM signal is sent, the ShutdownSignalBarrier handler class is called. However, as the ShutdownSignalBarrier's registered signal handler does not then call the previous handler (which is what is returned from the Signal.handle(..) method), the JDK does not then run its own shutdown hooks, which can break logic of applications that have other resources they would like to gracefully shut down. i.e. applications that call:

```java
Runtime.getRuntime().addShutdownHook(
        new Thread(() -> System.out.println("server shutting down"), "shutdown-thread"));
```

This is because the signal handler that is registered by default, (in the java.lang.Terminator class), is what is responsible for calling System.exit(code), which eventually runs the default JVM shutdown hooks.

In the ShutdownSignalBarrier class, a possible fix could then look like:

```java
public static final String[] SIGNAL_NAMES = { "INT", "TERM" };
private static final ArrayList<CountDownLatch> LATCHES = new ArrayList<>();

static
{
    for (final String signalName : SIGNAL_NAMES)
    {
        final var previous = Signal.handle(new Signal(signalName), (signal) -> {});
        Signal.handle(new Signal(signalName), (signal) -> {
            LATCHES.forEach(CountDownLatch::countDown);
            previous.handle(signal);
        });
    }
}
```

which would allow for the ShutdownSignalBarrier class to still take priority and run before any other handlers, but after completing it can then run the previously registered handler, allowing the JDK to run its shutdown hooks correctly. 

If this is an acceptable fix, I am happy to raise a PR and contribute to the library.

**Comment by vyazelenko** [comment]
PR merged.

**Comment by medusar** [comment]
In fact, there are 2 places will call the ShutdownHooks:

1. `Shutdown.exit()`, this method is called either by invoking `Runtime.exit()` manually, or by SIGINT or SIGTERM handler registered in `Terminator.setup()`. 
2. `Shutdown.shutdown()`, as it mentioned in its doc: ` Invoked by the JNI DestroyJavaVM procedure when the last non-daemon thread has finished`, it will be invoked automatically when there is no non-daemon threads in the JVM. 

After using `ShutdownSignalBarrier`, the SignalHandlers registered by `Terminator.setup()` is replaced, so the `Shutdown.exit()` method will not be called when the JVM is killed by signal `INT` or `TERM`, so the ShutdownHooks will not be called through `Shutdown.exit()`.

However, you can shutdown all your daemon threads when `ShutdownSignalBarrier.await()` is returned from blocking, this way, the `Shutdown.shutdown()` method will be called, so that all the ShutdownHooks can be called.


Here is the code:
```java 

import org.agrona.concurrent.Agent;
import org.agrona.concurrent.AgentRunner;
import org.agrona.concurrent.BusySpinIdleStrategy;
import org.agrona.concurrent.ShutdownSignalBarrier;

public class ExitDemo0 {
    public static void main(String[] args) throws InterruptedException {
//        use the ShutdownSignalBarrier to get notified when SIGTERM is received.
        ShutdownSignalBarrier barrier = new ShutdownSignalBarrier();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("shutdown hook invoked....");
        }));

        //create an AgentRunner to be closed when SIGTERM is received.
        var runner = new AgentRunner(new BusySpinIdleStrategy(), err -> err.printStackTrace(), null, new Agent() {
            @Override
            public int doWork() throws Exception {
                return 0;
            }

            @Override
            public String roleName() {
                return "agentxxx";
            }

            @Override
            public void onClose() {
                System.out.println("onClose");
            }
        });
        //start the agent runner, the thread here is a non-daemon thread.
        AgentRunner.startOnThread(runner);
        //wait for terminal signal
        barrier.await();
        System.out.println("Shutdown Signal received");

        //Here if we don't close the AgentRunner, the above ShutdownHook if not be called.
        //If we close the AgentRunner, the above ShutdownHook will be called.
//        CloseHelper.close(runner);
        System.out.println("finished");
    }
}
```

**Comment by mjpt777** [comment]
@medusar you should close all non-daemon threads regardless of using a signal hander or not. The code below is how we would recommend you would implement your `ExitDemo0`.

```java
import org.agrona.concurrent.Agent;
import org.agrona.concurrent.AgentRunner;
import org.agrona.concurrent.BusySpinIdleStrategy;
import org.agrona.concurrent.ShutdownSignalBarrier;

public class ExitDemo0
{
    public static void main(final String[] args)
    {
        final ShutdownSignalBarrier barrier = new ShutdownSignalBarrier();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> System.out.println("shutdown hook invoked...")));

        final Agent agent = new Agent()
        {
            public int doWork()
            {
                return 0;
            }

            public String roleName()
            {
                return "agentxxx";
            }

            public void onClose()
            {
                System.out.println("onClose");
            }
        };

        try (AgentRunner runner = new AgentRunner(
            BusySpinIdleStrategy.INSTANCE, Throwable::printStackTrace, null, agent))
        {
            AgentRunner.startOnThread(runner);

            barrier.await();
            System.out.println("Shutdown Signal received");
        }

        System.out.println("finished");
    }
}
```
