### ISSUE TITLE
ExpandableDirectByteBuffer maximum capacity only 1GB

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/agrona#272]
maximum capacity of ExpandableDirectByteBuffer is only 1GB
I think the reason is that the type of index is int
Do you think it's better to change int to long and expand the capacity?

![image](https://user-images.githubusercontent.com/1705403/215304596-6e764055-0a13-4f1b-a1f4-2b5837ad8b94.png)

**Comment by mikeb01** [comment]
This would require changing all of the accessor methods that take in a index value and switch it from a int to a long.  This in turn would break compatibility with the array backed implementations of the DirectBuffer.

**Comment by clayly** [comment]
> This would require changing all of the accessor methods that take in a index value and switch it from a int to a long. This in turn would break compatibility with the array backed implementations of the DirectBuffer.

What do you think, are there other pitfalls besides compatibility that prevent the increase in the maximum size? Only this limitation does not allow using Aeron in our project, where the buffer size must be at least 60 gigabytes.

**Comment by mjpt777** [comment]
ByteBuffer and byte arrays cannot be larger be larger than int capacity.

**Comment by clayly** [comment]
> ByteBuffer and byte arrays cannot be larger be larger than int capacity.

That is, if Argon would like to support a ring buffer of this size, then the only option is to work with files directly (memory-mapped files, dev/shm, etc.)?

**Comment by mjpt777** [comment]
>  > ByteBuffer and byte arrays cannot be larger be larger than int capacity.
> 
> That is, if Argon would like to support a ring buffer of this size, then the only option is to work with files directly (memory-mapped files, dev/shm, etc.)?

Mapped files in Java still return a `ByteBuffer` so still not possible. There are techniques that can be used which are unsupported in the JDK. We can provide commercial consulting on that but we do not provide it as free support in Agrona.

**Comment by vyazelenko** [comment]
First of all as pointed out @mjpt777 the underlying size cannot exceed `int` (an actual value is `Integer.MAX_VALUE - 8`). That being said we could allow `ExpandableDirectByteBuffer`to grow until that max value as oppose to 1GB.

If you need more than 2GB of storage you can use `org.agrona.concurrent.MappedResizeableBuffer`.
