### ISSUE TITLE
java.io.DataInput implementation for DirectBuffer-s

### ISSUE THREAD

**Issue by tkowalcz** [real-logic/agrona#273]
Currently Agrona has a `DirectBufferInputStream` which is a useful, bounds checked abstraction over `DirectBuffer` for cases when absolute performance is not needed and safety and allocation are more of a concern. 

However `InputStream` API is very crude and wrapping it using other JDK classes could introduce CPU overhead (exhibit A: `DataInputStream::readInt`).

Would you be interested in contribution of a `java.io.DataInput` implementation over raw `DirectBuffer`?

**Comment by mjpt777** [comment]
As a wrapper delegating to a `DirectBuffer` could be useful. Adding the methods to implement the interface would be wrong given `DirectBuffer` does not have position semantics.
