### ISSUE TITLE
ManyToOneRingBuffer that allows reading old messages like BroadcastBuffer but with multiple producers

### ISSUE THREAD

**Issue by tkowalcz** [real-logic/agrona#277]
Hi,

I was successfully using `ManyToOneRingBuffer` in our system. However I would like to be able to dump such buffer to file and inspect it's contents. Unfortunately it will zero out memory after message is read. I can use `BroadcastBuffer` instead but just noticed that it can have only one producer. Am I getting this right? Are there other options to achieve this? I kindly ask for advice.

Thanks!

**Comment by mjpt777** [comment]
Yes `BroadcastBuffer` is single producer.

To achieve this type of functionality you could use Aeron and setup an IPC Publication. This publication could be recorded by an Archive for later inspection. Aeron IPC provides even better throughput and latency than `ManyToOneRingBuffer` but is a bit more complicated to use.

**Comment by tkowalcz** [comment]
I have looked at `ManyToOneRingBuffer` and I think clearing out the buffer can be removed if the reader checks tail position to not go beyond valid data when reading. This would limit the scalability of the ring buffer and  has no place in this implementation and probably in agrona anyways. 

When I started looking for this functionality I thought its something more commonly used, now I see it's probably a fringe use case - I don't require absolute performance but don't want to take locks or allocate.

If you are curious these are my changes: https://github.com/real-logic/agrona/pull/278. I'll be testing this soon and we will use that variant in production I suppose.

**Comment by mjpt777** [comment]
This would not be safe. Offering a message is a two step process. First the space is claimed by incrementing the tail (producer position) then putting in the message. If the buffer was not zero'ed this the second step cannot be done atomically.
