### ISSUE TITLE
UnsafeBuffer - Slice

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#28]
Ability to get a sliced UnsafeBuffer.

E.g.
```
UnsafeBuffer slice = buff.slice(index, length)
```

**Comment by mjpt777** [comment]
This functionality is already provided via constructor and wrap method that takes a DirectBuffer.

**Comment by sirinath** [comment]
What if you wrap around an array? You just need to return a new wrapper with the internal memory offset and length updated.

**Comment by mjpt777** [comment]
@sirinath Please look at how the wrap methods and constructors work. All this functionality is available.  UnsafeBuffer is a view, it does not own the underlying or track it.
