### ISSUE TITLE
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code

### ISSUE THREAD

**Issue by medusar** [real-logic/agrona#280]
When using MarkFile, i got following error:
```
Exception in thread "main" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at java.base/java.io.PrintStream.println(PrintStream.java:955)
```

When i try this with Jdk11 or on linux or on Intel machines, it works,  when i use jdk17 and run on m1 chip, the error occurs.

Maybe it has some thing to do with memory alignments.

Jdk:
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

OS:
Chip Apple M1 Pro

Code to produce this error:
```java 
import org.agrona.MarkFile;
import org.agrona.concurrent.SystemEpochClock;

import java.io.File;

public class Main {
    public static void main(String[] args) {
        try (MarkFile markFile = new MarkFile(new File("a.dat"),
                true,
                0,
                8,
                112,
                0,
                SystemEpochClock.INSTANCE,
                (ignore) -> {
                },
                System.out::println)) {

            System.out.println(markFile.buffer().getLongVolatile(64));
            System.out.println(markFile.buffer().getLongVolatile(60));
        }
    }
}
```

**Comment by mjpt777** [comment]
Try removing:

```java
            System.out.println(markFile.buffer().getLongVolatile(60));
```

**Comment by medusar** [comment]
> Try removing:
> 
> ```java
>             System.out.println(markFile.buffer().getLongVolatile(60));
> ```

After removing this line, it works, does it have to be aligned with 8 bytes?

**Comment by mjpt777** [comment]
> After removing this line, it works, does it have to be aligned with 8 bytes?

Yes.
