### ISSUE TITLE
long index and length overloads

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#29]
Underlying Unsafe uses long indexes hence it makes sense to have long index overloads than just the int indexing and lengths you have now. 

For this to be really useful you will also need a way to to get the UnsafeBuffer to wrap around memory allocated through `allocateMemory`. Also for better safely a factory method to allocate and return an UnsafeBuffer

**Comment by mjpt777** [comment]
This functionality was considered and rejected in the design as the main usage is for wrapping a ByteBuffer.

**Comment by sirinath** [comment]
If you map multiple MappedByteBuffers then you can get a larger chunk of continuous memory this might be convenient to access as one peace. Currently I have ended up mapping 2 GB regions with 1 GB overlap so the largest byte range I can put is 1 GB. I am juggling multiple segments and offsets. All this will be solved if the indexing scheme becomes long
