### ISSUE TITLE
Map serialization and iteration order

### ISSUE THREAD

**Issue by fbaro** [real-logic/agrona#290]
I'm using the `Long2LongHashMap` in an Aeron Cluster instance. I think it's not possible to write the map to a snapshot and read it back while ensuring the iteration order is unchanged, and I think this is an issue for Aeron clusters.

The simplest test I can come up to demonstrate the issue is as follows:
```java
    @Test
    void iterationOrder() {
        final Long2LongHashMap m1 = new Long2LongHashMap(0);
        m1.put(7, 1);
        m1.put(14, 2);
        // Build m2 simulating a serialization and deserialization of m1
        final Long2LongHashMap m2 = new Long2LongHashMap(0);
        m1.forEachLong(m2::put);
        assertEquals(m1.keySet().iterator().nextValue(), m2.keySet().iterator().nextValue());
    }
``` 
Here I constructed a map in such a way that the two keys collide on the last element of the `Long2LongHashMap.entries` array. This makes the second key I add, `14`, end up in the first position of the array. When this map is iterated with `forEachLong`, `14` will be returned first, then `7`.

To serialize the map during a snapshot, I iterate it with the `forEachLong` method, and save the entries. To deserialize the map, I start from an empty map, and put the entries one by one. This behavior is simulated in the code above.

The test fails because I am adding to the reconstructed map first the `14` key (which this time is inserted at the end of the array), then the `7` key (which is inserted at the beginning). The iteration order of the deserialized map is therefore `7` first, `14` second - different from the original map.

Since serializing the `Long2LongHashMap` does not preserve iteration order, if a single node of an Aeron cluster dies and restarts from a snapshot, it can become out of sync with the nodes that are still up. I was unable however to think of any method to serialize the map without risking to change the iteration order.

**Comment by vyazelenko** [comment]
Agrona's Maps/Sets do not provide any iteration order guarantees. When taking a snapshot you need to sort your collection before writing snapshot messages or use a collection that preserve order. 

See also [1.2. Replication and Recovery](https://github.com/real-logic/aeron/wiki/Cluster-Tutorial#12-replication-and-recovery).

**Comment by fbaro** [comment]
Well... thanks for clarifying this.
