### ISSUE TITLE
Counter collision in CountersManager

### ISSUE THREAD

**Issue by pcdv** [real-logic/agrona#293]
Not 100% sure I'm using CountersManager correctly but this looks like a bug.
 * I create one counter in a manager, set a value in it, then close it
 * then, I create a new CountersManager on the same buffers
 * I open the first counter and check that the value is correct
 * I create another counter with a different registrationId and same typeId
 * I expect to find value 0 in counter, but I find the value found in the other counter

The problem goes away if I create both counters in the first manager (i.e. uncomment one line below)

Note that using a different typeId for the second counter does not fix the problem.

See test:
```java
package com.hsoft.aeron.egress;

import org.agrona.concurrent.UnsafeBuffer;
import org.agrona.concurrent.status.AtomicCounter;
import org.agrona.concurrent.status.CountersManager;
import org.agrona.concurrent.status.CountersReader;
import org.junit.Test;

import static java.nio.ByteBuffer.allocateDirect;
import static org.agrona.concurrent.status.CountersReader.COUNTER_LENGTH;
import static org.agrona.concurrent.status.CountersReader.METADATA_LENGTH;
import static org.junit.Assert.assertEquals;

public class CounterCollisionTest {

  public static final int SEQNUM_TYPE_ID = 3003;

  static AtomicCounter getCounter(CountersManager counters, int registrationId, int typeId, String label) {
    int counterId = counters.findByTypeIdAndRegistrationId(typeId, registrationId);
    if (counterId == CountersReader.NULL_COUNTER_ID) {
      AtomicCounter counter = counters.newCounter(label, typeId);
      counters.setCounterRegistrationId(counter.id(), registrationId);
      return counter;
    }
    else {
      return new AtomicCounter(counters.valuesBuffer(), counterId, counters);
    }
  }

  private static final int NUMBER_OF_COUNTERS = 4;

  /**
   * ET-34343 : two counters are created in a same manager, but one counter gets the
   * value of the other one.
   */
  @Test
  public void testCollision() {
    UnsafeBuffer metadataBuffer = new UnsafeBuffer(allocateDirect(NUMBER_OF_COUNTERS * METADATA_LENGTH));
    UnsafeBuffer valuesBuffer = new UnsafeBuffer(allocateDirect(NUMBER_OF_COUNTERS * COUNTER_LENGTH));

    {
      CountersManager mgr = new CountersManager(metadataBuffer, valuesBuffer);
      AtomicCounter seq1 = getCounter(mgr, 851, SEQNUM_TYPE_ID, "seq-85-1");

      assertEquals(0, seq1.get());
      seq1.set(1234);
      assertEquals(1234, seq1.get());

//      AtomicCounter seq0 = getCounter(mgr, 850, SEQNUM_TYPE_ID, "seq-85-0");

    }

    {
      CountersManager mgr = new CountersManager(metadataBuffer, valuesBuffer);
      AtomicCounter seq1 = getCounter(mgr, 851, SEQNUM_TYPE_ID, "seq-85-1");
      assertEquals(1234, seq1.get());

      AtomicCounter seq0 = getCounter(mgr, 850, SEQNUM_TYPE_ID, "seq-85-0");
      assertEquals(0, seq0.get());
    }
  }
}

```

**Comment by mikeb01** [comment]
This is not supported.  The documentation could be clearer on this, but we mention here: https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/status/CountersManager.java#L33 that counters need to be centrally managed.  There are aspects of the counters that aren't stored in the buffer (e.g. the free list).  It is intended to be single writer multiple reader (the counter increment is an ordered write not an atomic increment).

**Comment by pcdv** [comment]
Hi @mikeb01,

There might be some misunderstanding. This test is a minimal way to reproduce the same bug that happens in a more complicated setup, but still "centrally managed" as the counters are accessed from a single entity.

The buffers are obtained from a file. The first time the program runs, it creates some counters. Then, the program is restarted and creates more counters, which does not work as old counters are overwritten instead of creating new ones.

Is this scenario not supported?

**Comment by mikeb01** [comment]
> Is this scenario not supported?

Correct, the CountersManager/CountersReader weren't written to support persistence.  The memory map file was a means to share counters between processes.  Typically using an in-memory file system (e.g. /dev/shm).  The reason that the test fails is that the `highwaterMarkId` is not stored in the files or rebuilt on load.  Therefore when the second counter is allocated the id of the previous counter.

**Comment by pcdv** [comment]
Fair enough, not a bug if the tool is not used the way it was expected to be. But I thought recomputing the highwaterMarkId after opening the manager could be a possible enhancement.

Anyway, using CountersManager in my case is a bit overkill. I will explore other options.

For the context, I started using this class a couple years ago for persisting sequence numbers even though I wasn't totally sure it was a good idea (the doc mentions "counters that are normally stored in a memory-mapped file", which kind of implies persistence). And it did the job, so I forgot about it. Until some race condition caused the process to stop before it had time to create all counters, causing all kinds of strange bugs... Took me quite some time to find the root cause :)
