### ISSUE TITLE
LongHashSet Arrays.fill() is slow when used a bigger size init

### ISSUE THREAD

**Issue by liujingjun001** [real-logic/agrona#295]
![image](https://github.com/real-logic/agrona/assets/51243472/e2c961c6-d067-49de-a630-353a5fed44d3)

can remove this code?

**Comment by mjpt777** [comment]
No. This is required.

**Comment by vyazelenko** [comment]
Fixed with https://github.com/real-logic/agrona/commit/a49ea6713a0551ba61acb6f8358017b848fd3bd8.
