### ISSUE TITLE
Can you provide a JDK21 support plan? Currently, through my local compilation, I found that JDK17 can be supported, but JDK21 has compilation problems.

### ISSUE THREAD

**Issue by 1341005547** [real-logic/agrona#301]

**Comment by vyazelenko** [comment]
@1341005547 Agrona compiles and runs on JDK 17, 21, all the way to 24-ea. 

Are you seeing compilation issues while trying to compile Agrona itself or an application using Agrona?

**Comment by 1341005547** [comment]
There is no problem when Agrona 1.17.1 tries to compile JDK17, but when compiling JDK21, it is found that there are compilation problems. Which Agrona version do we currently support JDK21 from?

**Comment by mikeb01** [comment]
The latest stable release 1.23.0, https://github.com/real-logic/agrona/releases

**Comment by vyazelenko** [comment]
@1341005547 The first Agrona release that we started testing on JDK 21-ea was [1.19.0](https://github.com/real-logic/agrona/releases/tag/1.19.0). And in [1.20.0](https://github.com/real-logic/agrona/releases/tag/1.20.0) we've used JDK 21 GA for the first time.

That being said I would still recommend using the latest release, i.e. [1.23.0](https://github.com/real-logic/agrona/releases/tag/1.23.0-v2).
