### ISSUE TITLE
Why is this Acceptable

### ISSUE THREAD

**Issue by theodimop** [real-logic/agrona#302]
https://github.com/real-logic/agrona/blob/db6bb9205683baf3274bc0090940bb6defbf159a/agrona-concurrency-tests/src/main/java/org/agrona/concurrent/ringbuffer/OneToOneRingBufferTests.java#L102C9-L102C9

 @JCStressTest
    @Outcome(id = "19, 0", expect = Expect.ACCEPTABLE, desc = "Write before read")                         <- OK  
    @Outcome(id = "19, 42", expect = Expect.ACCEPTABLE, desc = "Read before write")                       <- OK
    @Outcome(id = "42, 0", expect = Expect.ACCEPTABLE, desc = "Write in the middle of the read")   <---- WHY ACCEPTABLE
    @State
    public static class WriteFullBuffer

If this is acceptable then the consumer will miss a message, which does not sound correct. Shouldn't it be FORBIDDEN?

Run the JCstress locally  (below spec) and that state is never observed. 

java.specification.vendor | Oracle Corporation
java.specification.version | 17
java.vendor | Azul Systems, Inc.
java.version | 17.0.12
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.vendor | Azul Systems, Inc.
java.vm.version | 17.0.12+7-LTS
os.arch | amd64
os.name | Linux
os.version | 6.8.0-44-generic

**Comment by vyazelenko** [comment]
@theodimop This is not acceptable. I've updated the test in https://github.com/real-logic/agrona/commit/f6c6d8be2cef3318d99ce31c347a3844d3c2acaa.
