### ISSUE TITLE
boundsCheck in UnsafeBuffer

### ISSUE THREAD

**Issue by kirtiteja** [real-logic/Agrona#31]
Would it be better to keep the SHOULD_BOUNDS_CHECK condition outside the boundsCheck method?
This way it might help inlining, boundsCheck method seem to be around 60 bytes.

**Comment by mjpt777** [comment]
It is a good point and something I've toyed with. It makes the code a lot more ugly to have it outside. Maybe worth more experiments.

**Comment by kirtiteja** [comment]
I noticed that setMemory method is missing the SHOULD_BOUNDS_CHECK if check. 
https://github.com/real-logic/Agrona/blob/4fdffc9929156540b2e60eefe949dc45f30f26d6/src/main/java/uk/co/real_logic/agrona/concurrent/UnsafeBuffer.java#L269

**Comment by mjpt777** [comment]
Thanks.
