### ISSUE TITLE
ManyToOneRingBuffer header is on the end of the buffer preventing use of constant offset counter fields

### ISSUE THREAD

**Issue by nitsanw** [real-logic/agrona#32]
At the moment the header is put at the end of the buffer, so we have:

```
    tailCounterIndex = capacity + RingBufferDescriptor.TAIL_COUNTER_OFFSET;
    headCounterIndex = capacity + RingBufferDescriptor.HEAD_COUNTER_OFFSET;
```

If the header was at the beginning of the buffer we could save ourselves all offset loads, E.g. instead of loading the tail counter like this:

```
load this.tailCounterIndex
load this.addressOffset
offset = addressOffset + tailCounterIndex
load offset
```

we could use a constant and eliminate the first load.

**Comment by mjpt777** [comment]
It is an interesting observation and probably worthwhile. This would mean that accesses to the buffer would have to have the offset for the header size added.

**Comment by mikeb01** [comment]
The header offset should be constant so you should be able to pre-add the value to the absolute address.  Or you could take the single contiguous block of memory and slice it into 2 AtomicBuffers one for the header and one for the data.

**Comment by mjpt777** [comment]
The interesting question I have is that all buffers have an address that the offset gets added to so we are not really dealing with a constant anyway. Will the "optimisations" actually make a difference?

**Comment by mikeb01** [comment]
That's kinda why I think the multiple buffers approach.  The offset gets added to the addressOffset on UnsafeBuffer.wrap, so should amount to the least amount of adding :-).  TBH, probably not a lot in it, the additional instructions are probably hidden in the pipeline.

**Comment by nitsanw** [comment]
@mikeb01 well... Mr. Smartypants didn't leave many big savings opportunities lying around now did he? ;-)
The savings are in theory a load and an add, as you can now completely pre-compute the index offset and need not use the base address. Given the buffer interface forces you to use the addressOffset we can't get that without an API change, so it's just the load.

**Comment by mjpt777** [comment]
The good part is the load is the more likely to stall the pipeline. We have 3-4 execution units that can do the add depending on which processor it runs on.

**Comment by nitsanw** [comment]
If you wanna go all fanatic about this we could generate the classes with embedded constants derived from the buffer base address and capacity :-) (there's no mad scientist laughter emoticon, hmm)

**Comment by mjpt777** [comment]
@nitsanw You will bring the wrath of the Maven zombies to your door.

**Comment by mjpt777** [comment]
This is not performance critical.

**Comment by mjpt777** [comment]
Having the fields at the end allows for extension without breaking existing code whereas new fields at the start would.
