### ISSUE TITLE
ManyToOneRingBuffer.read is loading tail to determine availability, could use data stream

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#33]
This is in line with the method utilized in the ManyToOneCAQ.
Reading the tail is detrimental to the progress of producers and is not likely to be a useful.
The reading loop after availability check utilizes the 'check data stream' method (like the SPSC/MPSC CAQ variants)
Is there any reason to keep the tail/availability check?

**Comment by mjpt777** [comment]
Good spot. Yes this algorithm would be simplified and made more efficient by taking this approach. I'll add it as an enhancement.

**Comment by nitsanw** [comment]
Will push in the change later

**Comment by mjpt777** [comment]
I've shaved off a few more 10s of nano seconds from the mean latency by caching the head value and this also improves throughput by saving a cache miss.
