### ISSUE TITLE
ManyToOneRingBuffer.read zeroing buffer after read, can that be made redundant?

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#34]
Currently a read may result in many messages being handled followed by a U.setMemory which will erase the contents of the messages. The motivation, I assume, would be security. Otherwise the contents are of no consequence as the producer is copying in rather than reusing the chunks of memory it gets allocated.
The only hole in this theory is that we expect the 'length' field in the (last +1) message to be 0. This is a problem in particular as the MTORB allows variable length messages (so the consumer zeroing the length is not possible). A potential solution is to separate the message length array from the data stream.

**Comment by mjpt777** [comment]
The Zero'ing is to ensure the message length will be zero for variable length messages.
