### ISSUE TITLE
ManyToOneRingBuffer headCache is on heap and adjacent to queue fields

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#35]
This means each update will perturb the otherwise immutable set of class fields. It is also on heap when all other queue data is offheap, though that can be a plus if the queue is used from multiple processes and each has it's own copy of a cached head.

**Comment by mjpt777** [comment]
Each update will only happen once per full lap round the ring buffer.

**Comment by nitsanw** [comment]
Not if the queue is fluttering near full (struggling consumer). It would happen every time the producers run out of cached values.

**Comment by mjpt777** [comment]
Yes. I'm already come to that conclusion and migrating to a different strategy.
