### ISSUE TITLE
MPSC/SPSC queues drain implementations delay the release of queue space

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#36]
This is problematic when due to what ever reason a large amount of work has built up in the queues.
This means that producers face the worse case of waiting for the consumer to work through the full queue capacity in order to be allowed a slot. The savings we get for delaying the availability of space in the queue is (arguably) marginal, as we're only sparing ourselves an ordered write of the head.
E.g. for SPSC we have:

        try
        {
            do
            {
                final long elementOffset = sequenceToBufferOffset(nextSequence, mask);
                final E item = (E)UNSAFE.getObjectVolatile(buffer, elementOffset);
                if (null == item)
                {
                    break;
                }

                UNSAFE.putOrderedObject(buffer, elementOffset, null);
                nextSequence++;
                elementHandler.accept(item);
            }
            while (true);
        }
        finally
        {
            UNSAFE.putOrderedLong(this, HEAD_OFFSET, nextSequence);
        }

Releasing the space in the queue as we go will be:

        do
        {
            final long elementOffset = sequenceToBufferOffset(nextSequence, mask);
            final E item = (E)UNSAFE.getObjectVolatile(buffer, elementOffset);
            if (null == item)
            {
                break;
            }

            UNSAFE.putOrderedObject(buffer, elementOffset, null);
            nextSequence++;
            UNSAFE.putOrderedLong(this, HEAD_OFFSET, nextSequence);
            elementHandler.accept(item);
        }
        while (true);

This suffers from the potential for theoretically never returning from drain. In JCTools this was resolved by imposing a limit on the number of elements drained.
Note that this problem has been concretely observed in systems under load and is not hypothetical.

**Comment by mjpt777** [comment]
Now that the head value is cached in both implementations, you are right on the benefits of delayed update. Previous throughput advantages are now achieved by better means.

**Comment by nitsanw** [comment]
cool, will fix in a second
