### ISSUE TITLE
ManyToOneRingBuffer read is only releasing full buffer at the end of read

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#37]
This is similar in spirit to #36 but complexity here lies in the release mechanism difference.
Where for the arrays element release overhead is fixed and already in the loop, for the ringbuffer the cost of clearing read elements is 2 fold, incrementing the head and filling the buffer with zero's. It is beneficial to zero the buffer in bulk (arguably it is also beneficial to null the array in bulk, but punt that discussion point) so it is perhaps unhelpful to clear one message at a time.
We could clear messages on either a fixed message count or read byte count to avoid this issue. Performance down side is less clear here, so needs further experimentation and testing of alternatives.

**Comment by mjpt777** [comment]
Given usage patterns in Aeron this is currently desired behaviour.
