### ISSUE TITLE
Allow Long2XX maps to return efficient sets for keySet()/valueSet()

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Agrona#38]
It would be useful to be able to do: 

    Long2LongHashMap map = new Long2LongHashMap(0);
    LongHashSet keys = map.longKeySet();

So that I don't need to auto unbox when iterating over the keys of a map.  Similarly for Ints on the Int2XX maps and for values on the Long2Long/Int2Int maps.

**Comment by RichardWarburton** [comment]
This is on my todo list as well actually. The IntHashSet/LongHashSet also need this optimization as well.

**Comment by mjpt777** [comment]
So just for the keys? Would the option to fill a Set but useful to save allocation?

```
LongHashSet keys = new LongHashSet();
map.getKeys(keys); // or similar?
```

**Comment by mjpt777** [comment]
I ask about the keys because for the values in the Int2Int etc. the values would also need boxed.

**Comment by mikeb01** [comment]
In an ideal world the keySet wouldn't be a copy.  However, if that is not possible then I'd probably not use it and stick using the primitive based forEach methods, e.g. intForEach on Int2IntMap.

**Comment by mjpt777** [comment]
@RichardWarburton Didn't you already do this?

**Comment by RichardWarburton** [comment]
Yes.
