### ISSUE TITLE
Infinite loop in IntHashSet when reached capacity

### ISSUE THREAD

**Issue by mtopolnik** [real-logic/Agrona#39]
Whenever the `IntHashSet`/`LongHashSet` reaches the requested capacity, it will enter an infinite loop searching for an empty slot (confirmed for capacities of 1 and 2). I would propose the following:

1. the set should keep operating correctly when it has reached the requested capacity;
2. it should either document its unusual failure mode or change it to an exception.

**Comment by mjpt777** [comment]
What version are you using? Is this a variation of https://github.com/real-logic/Agrona/issues/24 ?

**Comment by mtopolnik** [comment]
I reproduced this with Agrona's master. The reason is the same as in #24, however `IntHashSet` has fixed size. Current code will allow the length of the hashtable to equal the requested capacity, thus the load factor will degrade towards 1 and finally hit the infinite loop.

We fixed it in Hazelcast by applying a load factor of 1/2 and making `add` fail after reaching capacity.

**Comment by mjpt777** [comment]
@RichardWarburton Is there any reason these sets do not implement a load factor and auto resize like the maps?

**Comment by RichardWarburton** [comment]
Good question. The original motivating use-case for was storing sets of things where you knew the maximum number of elements that could be added. So for me I could just size it appropriately and not worry about it ever being full. It is documented that they are fixed size.

I've no objection to making them resizable - it just wasn't a requirement that I had, do you think we should support resizing in these sets? Its not hard to add to be honest. Thanks for spotting the non-termination behaviour @mtopolnik.

**Comment by mjpt777** [comment]
I think it is normal to expect a set to grow as things are add just like with a map. Having the load factor is also useful to control clustering around key hashes.

**Comment by mtopolnik** [comment]
I was actually fine with the fixed size (it matched my use case), but it was surprising and undocumented that the set wasn't allowed to reach the requested capacity.

**Comment by RichardWarburton** [comment]
@mjpt777 - do you think we should keep the fixed size hash set, and have a second that is growable, or just a single growable hashset?

**Comment by mjpt777** [comment]
Just a single one. If fixed size then surprising behaviour on add.

**Comment by RichardWarburton** [comment]
Ok, I'll put it on my todo list.

**Comment by RichardWarburton** [comment]
I've added resizing in 12df0b2b069c8e2ad05659a7e1a85fd157bb3af1.

Let me know if there's any issues that you spot. I've only done the resize-up case for adding, we aren't worrying about the resize-down case in removes for hashmaps so I've not implemented it here either.
