### ISSUE TITLE
UnsafeBuffer does not respect wrapped buffer ordering

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#40]
An UnsafeBuffer can wrap, or be constructed using an existing ByteBuffer. A ByteBuffer has an ordering (or rather a 'bigEndian' flag) but an UnsafeBuffer does not. This can yield some surprise should a ByteBuffer setup to a particular ordering (via ByteBuffer.ordering(ByteOrder)) be wrapped by an UnsafeBuffer.
UnsafeBuffer currently handles ordering as a JVM wide choice (via the NATIVE_BYTE_ORDER constant). We should either document this discrepancy (I think sprinkling some javadocs would be suffecient) or accommodate ordering choice by buffer.

**Comment by mjpt777** [comment]
UnsafeBuffer does not store state like ByteBuffer. This makes it thread safe. If you wish to set byte ordering other than the native setting then all the accessors have overloads.

I agree that some Javadoc is the best option.
