### ISSUE TITLE
DirectBuffer InputStream

### ISSUE THREAD

**Issue by robertroeser** [real-logic/Agrona#41]
Hi,

I have a use-case where I need to use an InputStream to access data using another library - Jackson in this case. The data I have is wrapped by a DirectBuffer, and it would be awesome if this could be exposed as an InputStream.

Thanks,
Robert

**Comment by mjpt777** [comment]
I'll experiment with putting an InputStream wrapper around a DirectBuffer to see if I can make it efficient. I think I can.

**Comment by robertroeser** [comment]
Here's what I came up with if it's helpful:
https://gist.github.com/robertroeser/ec1894f8749b5ffc4aa9

**Comment by mjpt777** [comment]
Do these implementations work for you?

**Comment by robertroeser** [comment]
I tried the DirectBufferInputStream but I'm getting IndexOutOfBoundsExceptions on line 132.

**Comment by mjpt777** [comment]
Sorry. Silly bug. Fixed.

**Comment by robertroeser** [comment]
Cools works perfectly - thanks!
