### ISSUE TITLE
Use Checker Framework | use @NotNull, @Nullable, etc.

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#42]
Can you consider using Checker Framework (http://types.cs.washington.edu/checker-framework/) than having checks in code.

**Comment by mjpt777** [comment]
Agrona does not have 3rd party dependencies. We plan to keep it that way for the foreseeable future.

**Comment by RichardWarburton** [comment]
Also, the checker framework isn't scheduled for inclusion into Javac anymore, so its not necessarily a good idea to rely on it being up to date with future Java language features.

@mjpt777 given that the not null annotations are small, we could use the gradle shadow plugin to bring in the findbugs module from maven central and still maintain the "no external dependencies" rule without bloating the jars.

**Comment by mjpt777** [comment]
@RichardWarburton I'm happy with external dependencies in the build and tests. We need to preserve no dependencies in the generated JAR.
