### ISSUE TITLE
Issue with head cache usage in ManyToOneRingBuffer

### ISSUE THREAD

**Issue by artyomkorzun** [real-logic/Agrona#43]
Please look at test. Claim method should recheck head when there is insufficient continuous space.

    @Test
    public void shouldInsertPaddingAndWriteToBuffer() {
        int padding = 200;
        int messageLength = 400;

        // buffer is free
        long tail = 2 * CAPACITY - padding;
        long head = tail;

        // free space is (200 + 300) more than message length (400) but contiguous space (300) is less than message length (400)
        long headCache = CAPACITY + 300;

        buffer.putLong(TAIL_COUNTER_INDEX, tail);
        buffer.putLong(HEAD_COUNTER_INDEX, head);
        buffer.putLong(HEAD_COUNTER_CACHE_INDEX, headCache);

        // all subsequent calls cant write message
        UnsafeBuffer srcBuffer = new UnsafeBuffer(new byte[messageLength]);
        assertTrue(ringBuffer.write(MSG_TYPE_ID, srcBuffer, 0, messageLength));
    }

**Comment by nitsanw** [comment]
Thanks for reporting and providing a test case + diagnosis enabling a quick fix :-).
