### ISSUE TITLE
Revise the documentation of Int/LongHashSet

### ISSUE THREAD

**Issue by mtopolnik** [real-logic/Agrona#44]
The docs on `Int`/`LongHashSet` have become stale:

>Fixed-size, garbage and allocation free long element specific hash set.

As of late the sets are no longer fixed-size and, as a conequence, no longer garbage- and allocation-free.

Another minor isseu in the generated `LongIterator`:

>An iterator for a sequence of primitive longegers.

**Comment by mjpt777** [comment]
Thanks @mtopolnik. The compiler and tests cannot catch comment bugs!

I also noticed the wrong hash function was used which would have resulted in double the probability of collisions which I've fixed.
