### ISSUE TITLE
TimerWheelTest > shouldBeAbleToCalculateDelayWithRealTime FAILED

### ISSUE THREAD

**Issue by kirtiteja** [real-logic/Agrona#45]
Checked out the trunk today and ran tests, the timer test failed. 
Ran the tests again a couple of times and they pass. Will update if I can reproduce, but the test does not seem to be deterministic.

![image](https://cloud.githubusercontent.com/assets/2222655/11407276/ae95aac6-9366-11e5-85da-e004866399a0.png)

**Comment by kirtiteja** [comment]
I ran the tests on a windows 7 desktop and hotspot jdk 8 update 65.

**Comment by mjpt777** [comment]
I've reverted to a more accurate calculation with this commit https://github.com/real-logic/Agrona/commit/a13b2ffea425d236123ad0dccd969bc910773bd8. Does this help?

In the past I've seen issues with Windows clocks related to accuracy and precision, at or below the millisecond level.

**Comment by tmontgomery** [comment]
It might be best to remove this test altogether. It isn't testing the functionality of the TimerWheel, but of the clock instead.
