### ISSUE TITLE
Agrona:0.4.8:uk.co.real_logic.agrona.collections missing 'L' sources.

### ISSUE THREAD

**Issue by EdwardBeckett** [real-logic/Agrona#47]
The lib jar and the sources jars are not in sync. For example, the Agrona-0.4.8-souces.jar is missing all of the source files under the collections package beginning with the letter, 'L'... respectively, 
Long2LongHashMap.java
Long2ObjectCache.java
Long2ObjectHashMap.java
LongHashSet.java
LongIterator.java
LongLongConsumer.java
LongLruCache.java

**Comment by mjpt777** [comment]
It was because the generated files were not included.

**Comment by EdwardBeckett** [comment]
Explains that. Thanks @mjpt777
