### ISSUE TITLE
ManyToManyConcurrentArrayQueue with capacity = 1

### ISSUE THREAD

**Issue by metanet** [real-logic/Agrona#48]
Hi,

I was playing with ManyToManyConcurrentArrayQueue and got confused about behaviour of the queue when I set its capacity to 1. 

My agrona version is 0.4.8 and here is my test:

```
import org.junit.Test;

import static org.junit.Assert.assertFalse;
import uk.co.real_logic.agrona.concurrent.ManyToManyConcurrentArrayQueue;

public class ManyToManyTest
{

    private ManyToManyConcurrentArrayQueue<Integer> queue = new ManyToManyConcurrentArrayQueue<>( 1 );

    @Test
    public void shouldNotOfferSecondInteger() {
        queue.offer( 1 );
        assertFalse(queue.offer( 2 ));
    }

}
```

``queue.offer(2)`` overwrites the first element and returns ``true``. Is ManyToMany queue with capacity=1 not supported (I check the source but couldn't see anything related to it) or am I missing something?

Thanks in advance

**Comment by mjpt777** [comment]
The algorithm is not designed for a size of 1. I'll look it tomorrow and put in check to ensure the capacity is sufficient.

**Comment by metanet** [comment]
yeah, that was my guess.

thanks a lot for the clarification
