### ISSUE TITLE
DirectBufferInputStream and MutableDirectBufferOutputStream length() method returns offset

### ISSUE THREAD

**Issue by loveyoupeng** [real-logic/Agrona#57]
/**
     * The length of the underlying buffer to use
     *
     * @return length of the underlying buffer to use
     */
    public int length()
    {
        return offset;
    }

**Comment by mjpt777** [comment]
Thanks.

**Comment by loveyoupeng** [comment]
my pleasure, I'm big fan of your work. just a quick question, why int Ringbufer  maxMsgLength = capacity / 8 ? my guess is due to alignment?

**Comment by mjpt777** [comment]
Just a pragmatic choice on max message size for the ring. Messages need to be contiguous and match alignment.
