### ISSUE TITLE
ManyToOneRingBuffer should verify/enforce buffer alignment to avoid unaligned and therefore not atomic reads/writes of counters

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#6]
Given that the requirement from supplied AtomicBuffer is:
The underlying buffer must a power of 2 in size plus sufficient space for the TRAILER_LENGTH.
And given that AtomicBuffer has no alignment guarantee, there is nothing stopping the counter alignment from straddling a cache line. E.g.:
new ManyToOneRingBuffer(new UnsafeBuffer(new byte[32*1024+TRAILER_LENGTH+1], 1, 32*1024+TRAILER_LENGTH+1));
The ring buffer will have capacity of 32K + trailer, but the start address is not aligned to anything. With slightly more effort you can construct an UnsafeBuffer such that counters are guaranteed to straddle the cache line.
One solution is to raise the capacity requirement by 1 cache line and force the RingBuffer start position to align to the cache line.

**Comment by mjpt777** [comment]
How can you determine cacheline alignment on a byte[]? Off heap and direct addresses it is possible.

With an array the best you can determine not word alignment based on JVM settings and array base offset?

**Comment by mjpt777** [comment]
Alignment needs to be a 8 byte boundaries for the largest access, i.e. a long. This can be confirmed by checking the `addressOffset`. The only way I can see how to create a buffer that is not word aligned is by passing in a direct address or by calling `ByteBuffer.splice()` that is not on a boundary. 

I've committed a fix that allows for `AtomicBuffer.verifyAlignment()` to be called from data structures requiring the `AtomicBuffer` methods.
