### ISSUE TITLE
UnsafeBuffer may not take offset into account

### ISSUE THREAD

**Issue by fkettwig** [real-logic/Agrona#60]
When calling

`public void wrap(final ByteBuffer buffer, final int offset, final int length)`

and the ByteBuffer is not a heap buffer, the offset is ignored:
```
else
{
     byteArray = null;
     addressOffset = BufferUtil.address(buffer);
}
```

**Comment by mjpt777** [comment]
Offheap the `addressOffset` is the real address with null for the `byteArray`. On heap the `addressOffset` is the offset from the `byteArray` reference/pointer. Neither are ignored. They are used appropriately given context.

**Comment by mjpt777** [comment]
If you look at the this test you can see each case being exercised.

https://github.com/real-logic/Agrona/blob/master/src/test/java/org/agrona/concurrent/AtomicBufferTest.java

**Comment by fkettwig** [comment]
But if I wanted to share an off-heap ByteBuffer, wouldn't the data be overwritten?
'''
ByteBuffer bb = ByteBuffer.allocateDirect(1024);
UnsafeBuffer ub1 = new UnsafeBuffer(bb, 0, 512);
UnsafeBuffer ub2 = new UnsafeBuffer(bb, 512, 512);
'''

**Comment by mjpt777** [comment]
Yes I see now. Forgive me for misreading earlier. Bad jetlag day ;-)

**Comment by mjpt777** [comment]
Thanks for the good find.

**Comment by mjpt777** [comment]
The current released version to Maven Central does not suffer from this issue. It was introduced while trying to address the Jigsaw issues. Unless someone is building from snapshot then they should be fine.
