### ISSUE TITLE
Will IntArrayList be added in the future?

### ISSUE THREAD

**Issue by guidomedina** [real-logic/Agrona#62]
I was wondering if primitive support for `List` is going to be added, it might not be very common and you could argue that a `Set` could do but sometimes you are just transferring a `List` of IDs and you know they are unique.

I was using Agrona but because it was missing `IntList` support I had to switch to `FastUtil` v7.x though it is too big for my needs.

**Comment by RichardWarburton** [comment]
Speaking from my own pov I try to only add things to Agrona if they are things that I plan to use myself. Would you be willing to contribute an implementation of an IntArrayList?

**Comment by guidomedina** [comment]
I can give it a try.

**Comment by mjpt777** [comment]
@guidomedina  I'm happy to review and help refine if you give it a go.

**Comment by guidomedina** [comment]
Thanks, I'll initially use as base implementation java.util.ArrayList (from Java 8 src) which is good enough, refine it for `int` type, annotate the local variables with `@DoNotSub`, copy and paste HastSetTests and re-adopt it to it.

I will get unto that tomorrow though.

**Comment by mjpt777** [comment]
You cannot copy from ArrayList due to licence. Remember Google.

**Comment by guidomedina** [comment]
ooook, but I'll re-use at least the same contracts, what users expect from `ArrayList` they should expect from `IntArrayList`

**Comment by mjpt777** [comment]
Apache Harmony has a better licence.

**Comment by mjpt777** [comment]
I've found I could often use such a list so I've added it. 

@guidomedina does this meet your needs?

**Comment by pjulien** [comment]
@mjpt777 

- Shouldn't the return values of ``indexOf`` and ``lastIndexOf`` be annotated with ``@DoNotSub``?
- ``ensureCapacity`` is private.  In both ``ArrayList`` and fastutil based lists, it's public.
- How do you remove an element without index? Use the boxed version?

**Comment by mjpt777** [comment]
@pjulien I've already addressed your 1 and 3 points. I just had not pushed them which I have now.

I can make ensureCapacity public.

**Comment by mjpt777** [comment]
@pjulien BTW thanks for the review and feedback.

**Comment by pjulien** [comment]
@mjpt777 

>  BTW thanks for the review and feedback.

No, thank you for the awesome library.  Not to mention the blog, the Google group, presentations, etc.

**Comment by guidomedina** [comment]
@mjpt777 I haven't looked the details so I will answer with another question, how close is it from mimic-ing `java.util.ArrayList`?

I believe that's kind of a good example, another example which is the library I'm using for `int` data structures for a trading system at the moment _-it is good but is too big for my taste hence I'm shading it-_ is:

http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/IntArrayList.html

**Comment by mjpt777** [comment]
It can completely mimic ArrayList with the additional ability provide unboxed methods. Check it out for yourself.
