### ISSUE TITLE
AbstractConcurrentArrayQueue last layer of padding is not enforced by inheritance

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#7]
This works out OK (I tested with JOL for java 8, compressed/uncompressed oops) but it is a fragile assumption (as experience would teach us: http://mechanical-sympathy.blogspot.com/2011/08/false-sharing-java-7.html). This can be resolved with an extra intermediate padding class.

**Comment by mjpt777** [comment]
You are of course correct. It was a quick stab at testing this week. Longer term strategy is required.

**Comment by nitsanw** [comment]
shall I throw in the fix?

**Comment by mjpt777** [comment]
You're very welcome :-)

**Comment by nitsanw** [comment]
fixed
