### ISSUE TITLE
IntHashSet.conjunction actually implements disjunction

### ISSUE THREAD

**Issue by wgromniak** [real-logic/Agrona#75]
I'm working with Agrona 0.5.4. I've discovered it because `IntHasSet.containsAll(Collection<?>)` returns `false` on an empty collection. The following code prints the values in comments:
```
IntHashSet set = new IntHashSet(-1);
System.out.println(set.containsAll(new IntHashSet(-1))); // true
System.out.println(set.containsAll((Collection<Integer>) new IntHashSet(-1))); // false
System.out.println(set.containsAll(new ArrayList<Integer>())); // false
```
which seems to be caused by what's mentioned in the title. `IntHashSet.addAll` and `IntHashSet.removeAll` use `IntHashSet.conjunction` with the correct outcome.

I'd be happy to fix this.

**Comment by RichardWarburton** [comment]
We would happily accept a pull request on this issue.

**Comment by wgromniak** [comment]
[Pull request](https://github.com/real-logic/Agrona/pull/77) created!
