### ISSUE TITLE
Behavior of getOrDefault in Agrona Maps is not consistent with behavior from standard JDK Maps

### ISSUE THREAD

**Issue by jessefugitt** [real-logic/Agrona#8]
With the new additions to the Map interface in Java 8, computeIfAbsent looks up the key and if it doesn't exist, it puts the computed value in the map before returning the computed value but getOrDefault never modifies the map (it simply returns the default value but does not do the put operation).  However, the Agrona implementations of the different Map classes all provide a getOrDefault method that is not consistent with the JDK behavior (because they also put the default value in the map before returning it).

Java 8
```
default V getOrDefault(Object key, V defaultValue) {
    V v;
    return (((v = get(key)) != null) || containsKey(key))
        ? v
        : defaultValue;
}
```

Agrona
```
public V getOrDefault(final long key, final Supplier<V> supplier)
{
        V value = get(key);
        if (value == null)
        {
            value = supplier.get();
            put(key, value);
        }
        return value;
}
```

This tripped me up when looking at the Aeron code (ActiveSubscriptions.java for example) because it wasn't apparent how the value returned from getOrDefault was being added to the Agrona map.  Although I sort of prefer the Agrona behavior over the Java 8 behavior, I think the function name in the Agrona classes should be changed to prevent confusion in the future for others since the behavior is not consistent with existing Java 8 Map classes.  Maybe getOrPutDefault or getOrDefaultAndPut or actually anything other than getOrDefault would be ideal.

**Comment by RichardWarburton** [comment]
I suspect that it should be named `computeIfAbsent`. Its doing the same behaviour as the regular `computeIfAbsent`, but with primitive specialised keys. And maybe worth making the function a `LongFunction<T>` rather than a `Supplier<T>`. By passing the key as a parameter we reduce the likelihood that people have to write capturing lambdas, thus following along with the guideline of Agrona as being a low GC/High performance library.

**Comment by RichardWarburton** [comment]
One implication of this fix is that when Agrona 0.3.2 is released and Aeron upgrades it might have to rename method calls appropriately.

**Comment by RichardWarburton** [comment]
Oh and thanks for spotting this @jessefugitt .

**Comment by jessefugitt** [comment]
I was going to look at fixing the few places in Aeron that would need to be changed after renaming the function but I see you've already done that as well so thanks @RichardWarburton.
