### ISSUE TITLE
SigIntBarrier needs a manual Signalling

### ISSUE THREAD

**Issue by guidomedina** [real-logic/Agrona#82]
I'm using `SigIntBarrier` in few micro-services and Aeron Media driver, now I see it is very useful but I don't have a way to manually signal the barrier if I want to shutdown using another way, a couple of questions:

- Isn't it cheaper the following way?
- Is there a technical reason why you prefer the park/unpark approach?

```
import sun.misc.Signal;

import java.util.concurrent.CountDownLatch;

public class SignalBarrier {

  final CountDownLatch latch = new CountDownLatch(1);

  public SignalBarrier() {
    Signal.handle(new Signal("INT"), (signal) -> signal());
  }

  public void signal() {
    latch.countDown();
  }

  public void await() {
    try {
      latch.await();
    } catch (InterruptedException ignored) {
    }
  }
}
```

**Comment by guidomedina** [comment]
OK, I follow your logic now, park/unpark really make sure the thread is really blocked, but then I would create a `signal()` method which could be called manually or from the `SignalHandler`

**Comment by guidomedina** [comment]
Can I PR this [commit](https://github.com/guidomedina/Agrona/commit/556e82c2538fb48a57bacde3c63fba810462351d)?

**Comment by guidomedina** [comment]
There are advantages on using a `CountDownLatch`, I noticed it also uses park/unpark so both will end up on a WAIT state, one advantage is that `SigIntBarrier` must be instantiated by the thread that will `await()` for the `SIGINT` where with the latch it can be instantiated anywhere and be passed around.

Maybe to avoid being interrupted it can introduce a `while (running) ...`

**Comment by mjpt777** [comment]
I've pushed a commit that should achieve the same result in a slightly cleaner fashion.

**Comment by guidomedina** [comment]
Thanks @mjpt777 closing issue.
