### ISSUE TITLE
SIGINT doesn't work under some conditions.

### ISSUE THREAD

**Issue by guidomedina** [real-logic/Agrona#83]
if I do:

`kill -INT $PID`

it doesn't work under Debian 8 or Ubuntu 16.04, now; with the following:

```
import sun.misc.Signal;
import sun.misc.SignalHandler;

import java.util.concurrent.CountDownLatch;

public class SignalBarrier {

  private final CountDownLatch latch = new CountDownLatch(1);

  public SignalBarrier() {
    final SignalHandler handler = (signal) -> signal();
    Signal.handle(new Signal("INT"), handler);
    Signal.handle(new Signal("TERM"), handler);
  }

  public void signal() {
    latch.countDown();
  }

  public void await() {
    try {
      latch.await();
    } catch (final InterruptedException ignore) {
      Thread.currentThread().interrupt();
    }
  }
}
```

when I do:

`kill -TERM $PID` or `kill $PID`

it works, the main reason for me using a `SIGTERM` or `SIGINT` is because `Aeron` has a shutdown hook making the node leaving an `Akka cluster` not leave correctly, the only method to shutdown properly now is by using a signal.

This was the best that I could come up with that seems to work.

**Comment by mjpt777** [comment]
What means did netty use for shutdown?

**Comment by guidomedina** [comment]
Hi Martin,

I have micro-services, before I used to use a standard JVM shutdown hook, the problem is that Aeron seems to have also a shutdown hook that was invoked before mine, so when my code tried to make Akka leave the cluster properly it was too late, making the cluster to not converge until further action was taken.

Netty doesn't have such shutdown hook because it is shutdown manually by Akka, same as Akka with Aeron in normal conditions, say; if you have a network shutdown (a command sent via HTTP for example)

But in my case is kind of special because I have small micro-services managed by `supervisord` which forward the Signal to the micro-services correctly, but someone SIGINT not working, I tested manually, maybe is a JDK 8 issue.

**Comment by guidomedina** [comment]
Maybe there should be an option to disable Aeron shutdown hook via system property? or maybe the opposite, be disabled by default?

**Comment by mjpt777** [comment]
To change the shutdown behaviour it is easy to write your own wrapper for starting the MediaDriver rather than use the default main. See the [LowLatencyMediaDriver](https://github.com/real-logic/Aeron/blob/master/aeron-samples/src/main/java/io/aeron/samples/LowLatencyMediaDriver.java) for a simple example.

**Comment by mjpt777** [comment]
Would it help to have a method on the `AeronClient` to shutdown the media driver. If so, then raise an issue for this.

**Comment by guidomedina** [comment]
I think yes such scenario will be nice, I think Akka guys are trying to work around the shutdown issue so maybe they need to be aware of it, it gets more complicated for Akka Sharding and other components that ned an orderly shutdown.

WDYT @patriknw

**Comment by patriknw** [comment]
We are working on a solution for coordinated shutdown of all the things. So far I have not seen the need to involve the SignalBarrier. We can now run ordinary jvm shutdown hooks for this in the right order. Let's discuss that in my akka PR.

When we launch the media driver embedded we can already shut it down so I don't have the need for that in the client api.

**Comment by guidomedina** [comment]
I did have a need because a standard JVM shutdown hook was causing the Aeron client (in my case using a shared driver) to shutdown before Akka was able to leave the cluster properly, that's the main reason I had to switch to a Signal.
