### ISSUE TITLE
please use lower case artifact id

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [real-logic/Agrona#86]
http://search.maven.org/#search%7Cga%7C1%7CAgrona

capital "A" interferes with various build pipelines

**Comment by mjpt777** [comment]
Fixed with this commit. https://github.com/real-logic/Agrona/commit/f4f66e36e9efb68bc4acc052a4ecb509907b33e7

**Comment by Andrei-Pozolotin** [comment]
thank you
