### ISSUE TITLE
OSGi manifest adjustment

### ISSUE THREAD

**Issue by briantopping** [real-logic/Agrona#87]
Hi all, happy new year.

Is it possible someone could adjust the OSGi manifests to not import `com.sun.media.sound`? If they are truly required, it might be best to make them an optional resolution.

I don't know Gradle or I'd send a PR.

Thanks! Brian

**Comment by tmontgomery** [comment]
This is being brought in via HighResolutionTimer.

**Comment by mjpt777** [comment]
I'll have a look at dynamically loading it so it is not an explicit dependency unless used.

**Comment by patriknw** [comment]
thanks
