### ISSUE TITLE
Support for unaligned access check in UnsafeBuffer/ExpandableArrayBuffer

### ISSUE THREAD

**Issue by m-anthony** [real-logic/Agrona#89]
Agrona buffers are using Unsafe.get/putXXX methods for memory accesses. If these accesses are unaligned, it can lead to performance and atomicity issue on architectures that allow such accesses, or crashes on other architectures.

While doing this without any check is acceptable for performance reasons, it might be interesting to have optional alignement checks to allow developers to test that their code cannot cause unaligned access (and especially if they are developing on x86, it will help to make sure that their code can run on all architectures without crash).

For instance, such a check can be helpful to develop unit tests proving that a SBE schema respects these alignment constraints.

I wonder if the trick used for the optional bound checks in UnsafeBuffer without impacting the compiled code can be used for this additional check too (probably with a "don't check access alignment" default value). In this case, I can submit a PR if needed.

**Comment by mjpt777** [comment]
Such a feature can be useful. I am concerned that increasing the size of the methods will impact their ability to be inlined. With this in mind a potentially better solution would be to add in this code by bytecode weaving in a debug build. This can be done with the likes of Byte Buddy. An example of this has been done in Aeron for debugging.

https://github.com/real-logic/Aeron/blob/master/aeron-samples/scripts/logging-media-driver.bat

https://github.com/real-logic/Aeron/tree/master/aeron-agent/src

**Comment by m-anthony** [comment]
I think you are right about the bytecode weaving approach being less harmful, since the feature will be mainly useful for dev/debug. Any chance to have this included in a future release ?

**Comment by mjpt777** [comment]
I'd be happy to accept a PR on this.

**Comment by m-anthony** [comment]
OK, I'm not used to such kind of bytecode manipulation tools, but I guess it is a good use case to start using them. I will try to provide a PR in the future :)

**Comment by mjpt777** [comment]
@m-anthony they are a really useful skill to add. They've helped me out so many times :-)

**Comment by m-anthony** [comment]
Quick question about the get/putStringXXX methods that first need to get/put the string length as an int.

Some of them are doing it directly through Unsafe, others are calling get/putInt()
Any particular reason behind this ? having all these methods calling get/putInt() will avoid the need to do specific check for these get/putStringXXX methods

**Comment by mjpt777** [comment]
They should not go via get/put int methods to reduce the virtual calls and additional bounds checks. I'll review.

**Comment by m-anthony** [comment]
Ok, so I'll assume that every string method that use an encoded size should have it's own alignement check in the agent.
