### ISSUE TITLE
Add an int counter map

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#90]
See potential usage/target in Aeron:
https://github.com/real-logic/Aeron/blob/4d3804f1b8bbbeee10d6b0540093905386df749a/aeron-driver/src/main/java/io/aeron/driver/media/ReceiveChannelEndpoint.java#L164-L164
```
   public int incRefToStream(final int streamId)
    {
        MutableInteger count = refCountByStreamIdMap.get(streamId);

        if (null == count)
        {
            count = new MutableInteger();
            refCountByStreamIdMap.put(streamId, count);
        }

        count.value++;

        return count.value;
    }

    public int decRefToStream(final int streamId)
    {
        final MutableInteger count = refCountByStreamIdMap.get(streamId);

        if (null == count)
        {
            throw new IllegalStateException("Could not find stream Id to decrement: " + streamId);
        }

        count.value--;

        if (0 == count.value)
        {
            refCountByStreamIdMap.remove(streamId);
        }

        return count.value;
    }
```
This can be done as a special cased int2int map

**Comment by mjpt777** [comment]
That makes sense. We should do it keyed by both int and long by generating like the others.

**Comment by nitsanw** [comment]
int2int counter is nice to do as a single array, similarly for long2long.
int2long and long2int are a bit awkward though, perhaps leave those for now.

**Comment by mjpt777** [comment]
For a counter the value should only be long I think.

**Comment by mjpt777** [comment]
You could as an easy solution just add the counting methods to int2intHashMap.

**Comment by nitsanw** [comment]
sounds good, adding 3 methods:
inc/dec/getAndAdd
missing value is the initial value unless you put a value in first.
