### ISSUE TITLE
RingBuffer: Let message handler decide on consumption

### ISSUE THREAD

**Issue by ThorbenLindhauer** [real-logic/Agrona#96]
I'd like to be able to decide in an implementation of `MessageHandler` whether the current message should be consumed. If not, then `RingBuffer#read` should return. This would be useful to handle backpressure that the consumer encounters.

Example: I have two ring buffers X and Y and three agents A, B, C. A produces into X, B consumes from X and produces into Y. C consumes from Y. Now if Y is saturated because C is busy, then I'd like to propagate backpressure up to X so that X eventually saturates and A stops producing into X.

I have no idea what the implications for implementation would be :)

**Comment by mjpt777** [comment]
Aeron supports this with the controlled poll. Why not move to that?

**Comment by ThorbenLindhauer** [comment]
Didn't really look into Aeron yet since we are building a custom solution for network transport on top of Agrona and SBE. I will certainly look into it, though. Which class would be the starting point for this?

**Comment by tmontgomery** [comment]
Check into the Image methods. https://github.com/real-logic/Aeron/blob/master/aeron-client/src/main/java/io/aeron/Image.java#L266

**Comment by mjpt777** [comment]
We have a system test which demonstrates this behaviour. Aeron is a network transport :-) and also works very well locally over IPC.

https://github.com/real-logic/Aeron/blob/master/aeron-system-tests/src/test/java/io/aeron/ControlledMessageTest.java
