### ISSUE TITLE
Int2IntHashMap methods don't work when using map via interface

### ISSUE THREAD

**Issue by vladimir-lifar** [real-logic/Agrona#98]
Some methods of Int2IntHashMap don't actually override corresponding methods of java.util.Map. Due to this fact we can't expose Int2IntHashMap as a Map<Integer, Integer> to external code.

computeIfAbsentUsingImplementation() works well, but computeIfAbsentUsingInterface() fails, because it uses java.util.Map.computeIfAbsent(...) which is not overridden.

    @Test
    public void computeIfAbsentUsingImplementation() {
        Int2IntHashMap int2IntHashMap = new Int2IntHashMap(-1);
        int key = 0;
        int result = int2IntHashMap.computeIfAbsent(key, k -> k);
        Assert.assertEquals(key, result);
    }

    @Test
    public void computeIfAbsentUsingInterface() {
        Map<Integer, Integer> map = new Int2IntHashMap(-1);
        int key = 0;
        int result = map.computeIfAbsent(key, k -> k);
        Assert.assertEquals(key, result);
    }

Agrona 0.9.3, JDK 8

**Comment by RichardWarburton** [comment]
You shouldn't need to override `computeIfAbsent`, should be fine to inherit the default if you implement the Map interface properly. Looks like we're not dealing with nulls properly on get() or put(). I'll take a look.

**Comment by RichardWarburton** [comment]
Thanks for the bug report.

**Comment by vladimir-lifar** [comment]
@RichardWarburton, many thanks for the fix!
